chore: i18n files url add version query parameter
awslabs/clickstream-analytics-on-aws pull request #1018
Opened 2024-04-02 14:14 UTC by tyyzqmf

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

## Summary

(describe what this merge request does)

## Implementation highlights

(describe how the merge request does for feature changes, share the RFC link if it has)

## Test checklist

- [ ] add new test cases
- [ ] all code changes are covered by unit tests
- [ ] end-to-end tests
  - [ ] deploy web console with CloudFront + S3 + API gateway
  - [ ] deploy web console within VPC
  - [ ] deploy ingestion server
    - [ ] with MSK sink
    - [ ] with KDS sink
    - [ ] with S3 sink
  - [ ] deploy data processing
  - [ ] deploy data modeling
    - [ ] new Redshift Serverless
    - [ ] provisioned Redshift
    - [ ] Athena
  - [ ] deploy with reporting
  - [ ] streaming ingestion
    - [ ] with Redshift Serverless
    - [ ] with provisioned Redshift

## Is it a breaking change

- [ ] add parameters without default value in stack
- [ ] introduce new service permission in stack
- [ ] introduce new top level stack module

## Miscellaneous

- [ ] introduce new symbol link source file(s) to be shared among infra code, web console frontend, and web console backend

2024-04-03 02:24 UTC, chenhaiyun approved these changes

2024-04-03 03:08 UTC, zxkane commented on frontend/.env
> +REACT_APP_SOLUTION_VERSION=
Is it a mandatory file?  Could we only set the environment variable `REACT_APP_SOLUTION_VERSION` when building frontend code?

2024-04-07 07:21 UTC, zxkane commented on .projenrc.js
> +  'env-cmd@^10.1.0',
Do we still need this tool?

2024-04-08 02:53 UTC, zxkane commented on src/cloudfront-control-plane-stack.ts
> +          'export REACT_APP_SOLUTION_VERSION=$REACT_APP_SOLUTION_VERSION',
Is it useless once you have already assigned the environment?

2024-04-08 05:48 UTC, zxkane requested changes
- [x] rebase and resolve locally

2024-04-08 13:37 UTC, zxkane approved these changes

2024-04-08 13:59 UTC, merged