feat: onboard streaming module
awslabs/clickstream-analytics-on-aws pull request #1024
Opened 2024-04-07 02:14 UTC by tyyzqmf

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

## Summary

(describe what this merge request does)

## Implementation highlights

(describe how the merge request does for feature changes, share the RFC link if it has)

## Test checklist

- [ ] add new test cases
- [ ] all code changes are covered by unit tests
- [ ] end-to-end tests
  - [ ] deploy web console with CloudFront + S3 + API gateway
  - [ ] deploy web console within VPC
  - [ ] deploy ingestion server
    - [ ] with MSK sink
    - [ ] with KDS sink
    - [ ] with S3 sink
  - [ ] deploy data processing
  - [ ] deploy data modeling
    - [ ] new Redshift Serverless
    - [ ] provisioned Redshift
    - [ ] Athena
  - [ ] deploy with reporting
  - [ ] streaming ingestion
    - [ ] with Redshift Serverless
    - [ ] with provisioned Redshift

## Is it a breaking change

- [ ] add parameters without default value in stack
- [ ] introduce new service permission in stack
- [ ] introduce new top level stack module

## Miscellaneous

- [ ] introduce new symbol link source file(s) to be shared among infra code, web console frontend, and web console backend

2024-04-08 10:28 UTC, zxkane requested changes
- [ ] polish UI wordings

2024-04-10 02:15 UTC, chenhaiyun commented on frontend/src/pages/pipelines/create/steps/DataProcessing.tsx
> +                        <Trans i18nKey="pipeline:create.enableStreamingDesc" />
Why not `defaultStr(t("pipeline:create.enableStreamingDesc"))`?

2024-04-10 02:15 UTC, chenhaiyun commented on frontend/src/pages/projects/detail/comp/ProjectPipeline.tsx
> +                        !selectedItems.length || !disableStreamEnableButton(),
`!selectedItems.length` is redundant.

2024-04-10 02:15 UTC, chenhaiyun commented on frontend/src/pages/projects/detail/comp/ProjectPipeline.tsx
> +                        !selectedItems.length || disableStreamEnableButton(),
`!selectedItems.length` is redundant.

2024-05-11 10:33 UTC, zxkane commented
### SonarQube Quality Gate Result
- **Result**: :white_check_mark: OK
- Triggered by @tyyzqmf on `pull_request`

| Metric | Status | Value | Error Threshold |
|:------:|:------:|:-----:|:---------------:|
|Reliability rating|:white_check_mark: OK|1|> 1|
|Security rating|:white_check_mark: OK|1|> 1|
|Sqale rating|:white_check_mark: OK|1|> 1|
|Coverage|:white_check_mark: OK|84|< 80|
|Duplicated lines density|:white_check_mark: OK|5|> 30|
|Blocker violations|:white_check_mark: OK|0|> 0|
|Bugs|:white_check_mark: OK|0|> 0|
|Code smells|:white_check_mark: OK|7|> 40|
|Critical violations|:white_check_mark: OK|0|> 0|
|Major violations|:white_check_mark: OK|0|> 0|
|Vulnerabilities|:white_check_mark: OK|0|> 0|

[View on SonarQube](http://sonarqube:9000/dashboard?id=pr-1024)
###### _updated: 5/11/2024, 10:33:35 (UTC+0)_

2024-05-11 10:33 UTC, zxkane commented
# SonarQube Code Analytics
## Quality Gate passed

![passed](https://hsonar.s3.ap-southeast-1.amazonaws.com/images/passed.png)

## Additional information
*The following metrics might not affect the Quality Gate status but improving them will improve your project code quality.*

## Issues
![bug](https://hsonar.s3.ap-southeast-1.amazonaws.com/images/bug.png)   [0 Bugs](http://sonarqube:9000/project/issues?id=pr-1024&resolved=false&sinceLeakPeriod=true&types=BUG)

![vulnerability](https://hsonar.s3.ap-southeast-1.amazonaws.com/images/vulnerability.png)   [0 Vulnerabilities](http://sonarqube:9000/project/issues?id=pr-1024&resolved=false&sinceLeakPeriod=true&types=VULNERABILITY)

![code_smell](https://hsonar.s3.ap-southeast-1.amazonaws.com/images/code_smell.png)   [0 Code Smells](http://sonarqube:9000/project/issues?id=pr-1024&resolved=false&sinceLeakPeriod=true&types=CODE_SMELL)

## Coverage and Duplications
*No data* **Coverage**

*No data* **Duplication**

2024-06-03 02:52 UTC, tyyzqmf commented on frontend/src/ts/utils.ts
> +      pipelineInfo?.enableStreaming ||
This module does not support closing like reporting module. If it is enabled, it cannot be closed.

2024-06-03 02:57 UTC, tyyzqmf commented on frontend/src/apis/application.ts
> +  const result: any = await apiRequest('put', `/app/${data.id}/stream`, data);
create app API:` POST /api/app`

2024-06-03 03:15 UTC, tyyzqmf commented on frontend/src/pages/projects/detail/comp/ProjectPipeline.tsx
> +                      confirmDeleteApplication();
added.

2024-06-03 07:05 UTC, zxkane commented
### SonarQube Quality Gate Result
- **Result**: :white_check_mark: OK
- Triggered by @tyyzqmf on `pull_request`

| Metric | Status | Value | Error Threshold |
|:------:|:------:|:-----:|:---------------:|
|Reliability rating|:white_check_mark: OK|1|> 1|
|Security rating|:white_check_mark: OK|1|> 1|
|Sqale rating|:white_check_mark: OK|1|> 1|
|Coverage|:white_check_mark: OK|83.60|< 80|
|Duplicated lines density|:white_check_mark: OK|5.20|> 30|
|Blocker violations|:white_check_mark: OK|0|> 0|
|Bugs|:white_check_mark: OK|0|> 0|
|Code smells|:white_check_mark: OK|9|> 40|
|Critical violations|:white_check_mark: OK|0|> 0|
|Major violations|:white_check_mark: OK|0|> 0|
|Vulnerabilities|:white_check_mark: OK|0|> 0|

[View on SonarQube](http://sonarqube:9000/dashboard?id=pr-1024)
###### _updated: 6/3/2024, 07:05:03 (UTC+0)_

2024-06-07 04:28 UTC, zxkane commented
### SonarQube Quality Gate Result
- **Result**: :exclamation: Error
- Triggered by @tyyzqmf on `pull_request`

| Metric | Status | Value | Error Threshold |
|:------:|:------:|:-----:|:---------------:|
|Reliability rating|:white_check_mark: OK|1|> 1|
|Security rating|:white_check_mark: OK|1|> 1|
|Sqale rating|:white_check_mark: OK|1|> 1|
|Coverage|:exclamation: Error|73.50|< 80|
|Duplicated lines density|:white_check_mark: OK|5.20|> 30|
|Blocker violations|:white_check_mark: OK|0|> 0|
|Bugs|:white_check_mark: OK|0|> 0|
|Code smells|:white_check_mark: OK|8|> 40|
|Critical violations|:white_check_mark: OK|0|> 0|
|Major violations|:white_check_mark: OK|0|> 0|
|Vulnerabilities|:white_check_mark: OK|0|> 0|

[View on SonarQube](http://sonarqube:9000/dashboard?id=pr-1024)
###### _updated: 6/7/2024, 04:28:18 (UTC+0)_

2024-06-07 05:04 UTC, zxkane commented
### SonarQube Quality Gate Result
- **Result**: :white_check_mark: OK
- Triggered by @zxkane on `pull_request`

| Metric | Status | Value | Error Threshold |
|:------:|:------:|:-----:|:---------------:|
|Reliability rating|:white_check_mark: OK|1|> 1|
|Security rating|:white_check_mark: OK|1|> 1|
|Sqale rating|:white_check_mark: OK|1|> 1|
|Coverage|:white_check_mark: OK|83.70|< 80|
|Duplicated lines density|:white_check_mark: OK|5.20|> 30|
|Blocker violations|:white_check_mark: OK|0|> 0|
|Bugs|:white_check_mark: OK|0|> 0|
|Code smells|:white_check_mark: OK|8|> 40|
|Critical violations|:white_check_mark: OK|0|> 0|
|Major violations|:white_check_mark: OK|0|> 0|
|Vulnerabilities|:white_check_mark: OK|0|> 0|

[View on SonarQube](http://sonarqube:9000/dashboard?id=pr-1024)
###### _updated: 6/7/2024, 05:04:50 (UTC+0)_

2024-06-07 05:07 UTC, chenhaiyun approved these changes

2024-06-07 05:59 UTC, zxkane requested changes

2024-06-07 05:59 UTC, zxkane commented on frontend/public/locales/zh-CN/application.json
> +    "tip1": "您确定要删除该应用程序 ",
Could we merge tip1 and tip2 and add placeholders for variable strings?

for example, https://github.com/awslabs/clickstream-analytics-on-aws/pull/1024/files#diff-a3cca7198752321283623781b842e9c87d263f0ba76c83514735cf73c3d6b97fR315

2024-06-07 05:59 UTC, zxkane commented on frontend/src/ts/utils.ts
> +    return templateVersion.greaterThan(SolutionVersion.V_1_1_5);
should be `greaterThanOrEquals(V_1_2_0)`

2024-06-08 02:53 UTC, zxkane commented
### SonarQube Quality Gate Result
- **Result**: :white_check_mark: OK
- Triggered by @tyyzqmf on `pull_request`

| Metric | Status | Value | Error Threshold |
|:------:|:------:|:-----:|:---------------:|
|Reliability rating|:white_check_mark: OK|1|> 1|
|Security rating|:white_check_mark: OK|1|> 1|
|Sqale rating|:white_check_mark: OK|1|> 1|
|Coverage|:white_check_mark: OK|83.50|< 80|
|Duplicated lines density|:white_check_mark: OK|5.20|> 30|
|Blocker violations|:white_check_mark: OK|0|> 0|
|Bugs|:white_check_mark: OK|0|> 0|
|Code smells|:white_check_mark: OK|8|> 40|
|Critical violations|:white_check_mark: OK|0|> 0|
|Major violations|:white_check_mark: OK|0|> 0|
|Vulnerabilities|:white_check_mark: OK|0|> 0|

[View on SonarQube](http://sonarqube:9000/dashboard?id=pr-1024)
###### _updated: 6/8/2024, 02:53:53 (UTC+0)_

2024-06-08 15:28 UTC, zxkane approved these changes

2024-06-08 15:57 UTC, merged