chore: add throttling statement into document
awslabs/clickstream-analytics-on-aws pull request #103
Opened 2023-07-28 08:55 UTC by dengmingtong

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

## Summary

Add throttling statement into document

## Implementation highlights

(describe how the merge request does for feature changes, share the RFC link if it has)

## Test checklist

- [ ] add new test cases
- [ ] all code changes are covered by unit tests
- [ ] end-to-end tests
  - [ ] deploy control plane with CloudFront + S3 + API gateway
  - [ ] deploy control plane within VPC
  - [ ] deploy ingestion server
    - [ ] with MSK sink
    - [ ] with KDS sink
    - [ ] with S3 sink
  - [ ] deploy data processing
  - [ ] deploy data modeling
    - [ ] new Redshift Serverless
    - [ ] provisioned Redshift
    - [ ] Athena
  - [ ] deploy with reporting

## Is it a breaking change

- [ ] add parameters without default value in stack
- [ ] introduce new service permission in stack
- [ ] introduce new top level stack module

2023-07-29 03:56 UTC, zxkane requested changes

2023-07-29 03:56 UTC, zxkane commented on docs/en/pipeline-mgmt/ingestion/index.md
> +Currently, there is no built-in throttling feature available with this solution. If you require throttling feature, you can configure WAF to implement throttling feature. Please refer [WAF][waf] docu
update first `WAF` to `AWS WAF`

2023-07-31 02:06 UTC, dengmingtong commented on docs/en/pipeline-mgmt/ingestion/index.md
> +Currently, there is no built-in throttling feature available with this solution. If you require throttling feature, you can configure WAF to implement throttling feature. Please refer [WAF][waf] docu
Fixed

2023-07-31 06:29 UTC, zxkane approved these changes

2023-07-31 06:29 UTC, merged