chore: modify SQL to handle abnormal data in retention view
awslabs/clickstream-analytics-on-aws pull request #1054
Opened 2024-04-13 09:46 UTC by llmin

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

## Summary

(describe what this merge request does)

## Implementation highlights

(describe how the merge request does for feature changes, share the RFC link if it has)

## Test checklist

- [ ] add new test cases
- [ ] all code changes are covered by unit tests
- [ ] end-to-end tests
  - [ ] deploy web console with CloudFront + S3 + API gateway
  - [ ] deploy web console within VPC
  - [ ] deploy ingestion server
    - [ ] with MSK sink
    - [ ] with KDS sink
    - [ ] with S3 sink
  - [ ] deploy data processing
  - [ ] deploy data modeling
    - [ ] new Redshift Serverless
    - [ ] provisioned Redshift
    - [ ] Athena
  - [ ] deploy with reporting
  - [ ] streaming ingestion
    - [ ] with Redshift Serverless
    - [ ] with provisioned Redshift

## Is it a breaking change

- [ ] add parameters without default value in stack
- [ ] introduce new service permission in stack
- [ ] introduce new top level stack module

## Miscellaneous

- [ ] introduce new symbol link source file(s) to be shared among infra code, web console frontend, and web console backend

2024-04-13 13:14 UTC, zxkane requested changes
- [ ] update end-to-end test result for a clean deployment

2024-04-13 13:14 UTC, zxkane commented on src/analytics/private/sqls/redshift/dashboard/clickstream_retention_view_v3.sql
> +    FROM shop.clickstream_retention_base_view_test
What is it?

2024-04-13 13:50 UTC, llmin commented on src/analytics/private/sqls/redshift/dashboard/clickstream_retention_view_v3.sql
> +    FROM shop.clickstream_retention_base_view_test
fixed

2024-04-14 05:13 UTC, zxkane approved these changes

2024-04-14 05:36 UTC, merged