chore(schema): support multi group condition
awslabs/clickstream-analytics-on-aws pull request #1075
Opened 2024-04-17 06:56 UTC by llmin

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

## Summary

(describe what this merge request does)

## Implementation highlights

(describe how the merge request does for feature changes, share the RFC link if it has)

## Test checklist

- [ ] add new test cases
- [ ] all code changes are covered by unit tests
- [ ] end-to-end tests
  - [ ] deploy web console with CloudFront + S3 + API gateway
  - [ ] deploy web console within VPC
  - [ ] deploy ingestion server
    - [ ] with MSK sink
    - [ ] with KDS sink
    - [ ] with S3 sink
  - [ ] deploy data processing
  - [ ] deploy data modeling
    - [ ] new Redshift Serverless
    - [ ] provisioned Redshift
    - [ ] Athena
  - [ ] deploy with reporting
  - [ ] streaming ingestion
    - [ ] with Redshift Serverless
    - [ ] with provisioned Redshift

## Is it a breaking change

- [ ] add parameters without default value in stack
- [ ] introduce new service permission in stack
- [ ] introduce new top level stack module

## Miscellaneous

- [ ] introduce new symbol link source file(s) to be shared among infra code, web console frontend, and web console backend

2024-04-17 06:57 UTC, llmin commented
@tyyzqmf  Please add frontend update in this PR.

2024-04-17 15:02 UTC, zxkane requested changes

2024-04-17 15:10 UTC, llmin commented on src/control-plane/backend/lambda/api/service/quicksight/reporting-check.ts
> +        if (condition.dataType !== MetadataValueType.STRING) {
We only support grouping conditions of type String. The addition of boolean was recently added, but the visual in QuickSight does not support this type.

2024-04-22 09:35 UTC, zxkane approved these changes

2024-04-22 14:50 UTC, zxkane approved these changes

2024-04-22 15:47 UTC, merged