fix: page view count miss match
awslabs/clickstream-analytics-on-aws pull request #1325
Opened 2024-05-16 11:00 UTC by llmin

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

## Summary

(describe what this merge request does)

## Implementation highlights

(describe how the merge request does for feature changes, share the RFC link if it has)

## Test checklist

- [ ] add new test cases
- [ ] all code changes are covered by unit tests
- [ ] end-to-end tests
  - [ ] deploy web console with CloudFront + S3 + API gateway
  - [ ] deploy web console within VPC
  - [ ] deploy ingestion server
    - [ ] with MSK sink
    - [ ] with KDS sink
    - [ ] with S3 sink
  - [ ] deploy data processing
  - [ ] deploy data modeling
    - [ ] new Redshift Serverless
    - [ ] provisioned Redshift
    - [ ] Athena
  - [ ] deploy with reporting
  - [ ] streaming ingestion
    - [ ] with Redshift Serverless
    - [ ] with provisioned Redshift

## Is it a breaking change

- [ ] add parameters without default value in stack
- [ ] introduce new service permission in stack
- [ ] introduce new top level stack module

## Miscellaneous

- [ ] introduce new symbol link source file(s) to be shared among infra code, web console frontend, and web console backend

2024-05-17 08:03 UTC, zxkane commented
### SonarQube Quality Gate Result
- **Result**: :exclamation: Error
- Triggered by @llmin on `pull_request`

| Metric | Status | Value | Error Threshold |
|:------:|:------:|:-----:|:---------------:|
|Reliability rating|:white_check_mark: OK|1|> 1|
|Security rating|:white_check_mark: OK|1|> 1|
|Sqale rating|:white_check_mark: OK|1|> 1|
|Coverage|:white_check_mark: OK|83.60|< 80|
|Duplicated lines density|:white_check_mark: OK|5.20|> 30|
|Blocker violations|:white_check_mark: OK|0|> 0|
|Bugs|:white_check_mark: OK|0|> 0|
|Code smells|:white_check_mark: OK|27|> 40|
|Critical violations|:white_check_mark: OK|0|> 0|
|Major violations|:exclamation: Error|19|> 0|
|Vulnerabilities|:white_check_mark: OK|0|> 0|

[View on SonarQube](http://sonarqube:9000/dashboard?id=pr-1325)
###### _updated: 5/17/2024, 08:03:36 (UTC+0)_

2024-05-17 08:03 UTC, zxkane commented
# SonarQube Code Analytics
## Quality Gate failed

![failed](https://hsonar.s3.ap-southeast-1.amazonaws.com/images/failed.png)

## Additional information
*The following metrics might not affect the Quality Gate status but improving them will improve your project code quality.*

## Issues
![bug](https://hsonar.s3.ap-southeast-1.amazonaws.com/images/bug.png)   [0 Bugs](http://sonarqube:9000/project/issues?id=pr-1325&resolved=false&sinceLeakPeriod=true&types=BUG)

![vulnerability](https://hsonar.s3.ap-southeast-1.amazonaws.com/images/vulnerability.png)   [0 Vulnerabilities](http://sonarqube:9000/project/issues?id=pr-1325&resolved=false&sinceLeakPeriod=true&types=VULNERABILITY)

![code_smell](https://hsonar.s3.ap-southeast-1.amazonaws.com/images/code_smell.png)   [0 Code Smells](http://sonarqube:9000/project/issues?id=pr-1325&resolved=false&sinceLeakPeriod=true&types=CODE_SMELL)

## Coverage and Duplications
*No data* **Coverage**

*No data* **Duplication**

2024-05-17 08:05 UTC, zxkane commented
### SonarQube Quality Gate Result
- **Result**: :exclamation: Error
- Triggered by @llmin on `pull_request`

| Metric | Status | Value | Error Threshold |
|:------:|:------:|:-----:|:---------------:|
|Reliability rating|:white_check_mark: OK|1|> 1|
|Security rating|:white_check_mark: OK|1|> 1|
|Sqale rating|:white_check_mark: OK|1|> 1|
|Coverage|:white_check_mark: OK|83.60|< 80|
|Duplicated lines density|:white_check_mark: OK|5.20|> 30|
|Blocker violations|:white_check_mark: OK|0|> 0|
|Bugs|:white_check_mark: OK|0|> 0|
|Code smells|:white_check_mark: OK|27|> 40|
|Critical violations|:white_check_mark: OK|0|> 0|
|Major violations|:exclamation: Error|19|> 0|
|Vulnerabilities|:white_check_mark: OK|0|> 0|

[View on SonarQube](http://sonarqube:9000/dashboard?id=pr-1325)
###### _updated: 5/17/2024, 08:05:12 (UTC+0)_

2024-05-17 08:21 UTC, zxkane requested changes

2024-05-17 08:21 UTC, zxkane commented on src/main.ts
> +// import { ApplicationLoadBalancerControlPlaneStack } from './alb-control-plane-stack';
revert unwanted changes

2024-05-17 08:21 UTC, zxkane commented on src/reporting/lambda/custom-resource/quicksight/index.ts
> +        // throw err;
don't ignore the exception

2024-05-17 08:21 UTC, zxkane commented on src/reporting/lambda/custom-resource/quicksight/index.ts
> +    if (refreshInterval === RefreshInterval.HOURLY) {
assign a variable to  `RefreshInterval.DAILY` or `HOURLY`, then share the code to create schedule

2024-05-17 12:33 UTC, zxkane commented
### SonarQube Quality Gate Result
- **Result**: :white_check_mark: OK
- Triggered by @llmin on `pull_request`

| Metric | Status | Value | Error Threshold |
|:------:|:------:|:-----:|:---------------:|
|Reliability rating|:white_check_mark: OK|1|> 1|
|Security rating|:white_check_mark: OK|1|> 1|
|Sqale rating|:white_check_mark: OK|1|> 1|
|Coverage|:white_check_mark: OK|83.60|< 80|
|Duplicated lines density|:white_check_mark: OK|5.20|> 30|
|Blocker violations|:white_check_mark: OK|0|> 0|
|Bugs|:white_check_mark: OK|0|> 0|
|Code smells|:white_check_mark: OK|8|> 40|
|Critical violations|:white_check_mark: OK|0|> 0|
|Major violations|:white_check_mark: OK|0|> 0|
|Vulnerabilities|:white_check_mark: OK|0|> 0|

[View on SonarQube](http://sonarqube:9000/dashboard?id=pr-1325)
###### _updated: 5/17/2024, 12:33:40 (UTC+0)_

2024-05-17 14:39 UTC, zxkane approved these changes

2024-05-19 04:37 UTC, tyyzqmf approved these changes

2024-05-19 05:20 UTC, merged