docs: add troubleshoot for failing to create emr application in the
awslabs/clickstream-analytics-on-aws pull request #1336
Opened 2024-05-19 08:05 UTC by zxkane

specified subnets

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

## Summary

(describe what this merge request does)

## Implementation highlights

(describe how the merge request does for feature changes, share the RFC link if it has)

## Test checklist

- [ ] add new test cases
- [ ] all code changes are covered by unit tests
- [ ] end-to-end tests
  - [ ] deploy web console with CloudFront + S3 + API gateway
  - [ ] deploy web console within VPC
  - [ ] deploy ingestion server
    - [ ] with MSK sink
    - [ ] with KDS sink
    - [ ] with S3 sink
  - [ ] deploy data processing
  - [ ] deploy data modeling
    - [ ] new Redshift Serverless
    - [ ] provisioned Redshift
    - [ ] Athena
  - [ ] deploy with reporting
  - [ ] streaming ingestion
    - [ ] with Redshift Serverless
    - [ ] with provisioned Redshift

## Is it a breaking change

- [ ] add parameters without default value in stack
- [ ] introduce new service permission in stack
- [ ] introduce new top level stack module

## Miscellaneous

- [ ] introduce new symbol link source file(s) to be shared among infra code, web console frontend, and web console backend

2024-05-19 08:38 UTC, zxkane commented
### SonarQube Quality Gate Result
- **Result**: :white_check_mark: OK
- Triggered by @zxkane on `pull_request`

| Metric | Status | Value | Error Threshold |
|:------:|:------:|:-----:|:---------------:|
|Reliability rating|:white_check_mark: OK|1|> 1|
|Security rating|:white_check_mark: OK|1|> 1|
|Sqale rating|:white_check_mark: OK|1|> 1|
|Coverage|:white_check_mark: OK|83.40|< 80|
|Duplicated lines density|:white_check_mark: OK|5.60|> 30|
|Blocker violations|:white_check_mark: OK|0|> 0|
|Bugs|:white_check_mark: OK|0|> 0|
|Code smells|:white_check_mark: OK|1|> 40|
|Critical violations|:white_check_mark: OK|0|> 0|
|Major violations|:white_check_mark: OK|0|> 0|
|Vulnerabilities|:white_check_mark: OK|0|> 0|

[View on SonarQube](http://sonarqube:9000/dashboard?id=pr-1336)
###### _updated: 5/19/2024, 08:38:11 (UTC+0)_

2024-05-19 08:38 UTC, zxkane commented
# SonarQube Code Analytics
## Quality Gate passed

![passed](https://hsonar.s3.ap-southeast-1.amazonaws.com/images/passed.png)

## Additional information
*The following metrics might not affect the Quality Gate status but improving them will improve your project code quality.*

## Issues
![bug](https://hsonar.s3.ap-southeast-1.amazonaws.com/images/bug.png)   [0 Bugs](http://sonarqube:9000/project/issues?id=pr-1336&resolved=false&sinceLeakPeriod=true&types=BUG)

![vulnerability](https://hsonar.s3.ap-southeast-1.amazonaws.com/images/vulnerability.png)   [0 Vulnerabilities](http://sonarqube:9000/project/issues?id=pr-1336&resolved=false&sinceLeakPeriod=true&types=VULNERABILITY)

![code_smell](https://hsonar.s3.ap-southeast-1.amazonaws.com/images/code_smell.png)   [0 Code Smells](http://sonarqube:9000/project/issues?id=pr-1336&resolved=false&sinceLeakPeriod=true&types=CODE_SMELL)

## Coverage and Duplications
*No data* **Coverage**

*No data* **Duplication**

2024-05-20 01:43 UTC, luorobin-a2z commented on docs/en/troubleshooting.md
> +## Problem: When configuring the data pipeline with data processing enabled, the data processing CloudFormation stack encountered the error "The availability zones for subnets [subnet-xyz] are curren
--> ##Problem: When creating the data pipeline with data processing enabled, the data processing CloudFormation stack encountered error of "The availability zones for subnets [subnet-xyz] are currently not supported.".

2024-05-20 01:43 UTC, luorobin-a2z commented on docs/en/troubleshooting.md
> +The EMR serverless application for processing the clickstream data cannot be deployed in the specified private subnets mentioned in the above error message.
--> This is due to the EMR serverless application for processing the clickstream data cannot be deployed in the specified private subnets mentioned in the above error message.

2024-05-20 01:47 UTC, luorobin-a2z commented on docs/zh/troubleshooting.md
> +
问题: 在创建启用数据处理的数据管道时，数据处理 CloudFormation 堆栈遇到了错误 "The availability zones for subnets [subnet-xyz] are currently not supported."。

2024-05-20 01:48 UTC, luorobin-a2z commented on docs/zh/troubleshooting.md
> +处理点击流数据的 EMR 无服务器应用程序无法部署在上述错误消息中指定的私有子网中。
这是因为处理点击流数据的 EMR 无服务器应用程序无法部署在上述错误消息中指定的私有子网中。

2024-05-20 01:48 UTC, luorobin-a2z requested changes
wording update

2024-05-20 03:32 UTC, zxkane commented
### SonarQube Quality Gate Result
- **Result**: :white_check_mark: OK
- Triggered by @zxkane on `pull_request`

| Metric | Status | Value | Error Threshold |
|:------:|:------:|:-----:|:---------------:|
|Reliability rating|:white_check_mark: OK|1|> 1|
|Security rating|:white_check_mark: OK|1|> 1|
|Sqale rating|:white_check_mark: OK|1|> 1|
|Coverage|:white_check_mark: OK|83.40|< 80|
|Duplicated lines density|:white_check_mark: OK|5.60|> 30|
|Blocker violations|:white_check_mark: OK|0|> 0|
|Bugs|:white_check_mark: OK|0|> 0|
|Code smells|:white_check_mark: OK|1|> 40|
|Critical violations|:white_check_mark: OK|0|> 0|
|Major violations|:white_check_mark: OK|0|> 0|
|Vulnerabilities|:white_check_mark: OK|0|> 0|

[View on SonarQube](http://sonarqube:9000/dashboard?id=pr-1336)
###### _updated: 5/20/2024, 03:32:36 (UTC+0)_

2024-05-20 03:33 UTC, zxkane commented
### SonarQube Quality Gate Result
- **Result**: :white_check_mark: OK
- Triggered by @zxkane on `pull_request`

| Metric | Status | Value | Error Threshold |
|:------:|:------:|:-----:|:---------------:|
|Reliability rating|:white_check_mark: OK|1|> 1|
|Security rating|:white_check_mark: OK|1|> 1|
|Sqale rating|:white_check_mark: OK|1|> 1|
|Coverage|:white_check_mark: OK|83.40|< 80|
|Duplicated lines density|:white_check_mark: OK|5.60|> 30|
|Blocker violations|:white_check_mark: OK|0|> 0|
|Bugs|:white_check_mark: OK|0|> 0|
|Code smells|:white_check_mark: OK|1|> 40|
|Critical violations|:white_check_mark: OK|0|> 0|
|Major violations|:white_check_mark: OK|0|> 0|
|Vulnerabilities|:white_check_mark: OK|0|> 0|

[View on SonarQube](http://sonarqube:9000/dashboard?id=pr-1336)
###### _updated: 5/20/2024, 03:33:55 (UTC+0)_

2024-05-21 07:21 UTC, luorobin-a2z approved these changes

2024-05-21 08:16 UTC, merged