docs: update migration data procedures
awslabs/clickstream-analytics-on-aws pull request #1386
Opened 2024-05-26 08:04 UTC by zxkane

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

## Summary

(describe what this merge request does)

## Implementation highlights

(describe how the merge request does for feature changes, share the RFC link if it has)

## Test checklist

- [ ] add new test cases
- [ ] all code changes are covered by unit tests
- [ ] end-to-end tests
  - [ ] deploy web console with CloudFront + S3 + API gateway
  - [ ] deploy web console within VPC
  - [ ] deploy ingestion server
    - [ ] with MSK sink
    - [ ] with KDS sink
    - [ ] with S3 sink
  - [ ] deploy data processing
  - [ ] deploy data modeling
    - [ ] new Redshift Serverless
    - [ ] provisioned Redshift
    - [ ] Athena
  - [ ] deploy with reporting
  - [ ] streaming ingestion
    - [ ] with Redshift Serverless
    - [ ] with provisioned Redshift

## Is it a breaking change

- [ ] add parameters without default value in stack
- [ ] introduce new service permission in stack
- [ ] introduce new top level stack module

## Miscellaneous

- [ ] introduce new symbol link source file(s) to be shared among infra code, web console frontend, and web console backend

2024-05-26 08:25 UTC, luorobin-a2z commented on docs/en/upgrade.md
> +        If the volume of migrated data is large, it is recommended to refresh the `clickstream_event_base_view` in batches. That is, based on the occurrence time of the events, call the following sto
最好能给一下多大 是large

2024-05-26 08:25 UTC, luorobin-a2z approved these changes

2024-05-26 08:38 UTC, zxkane commented
### SonarQube Quality Gate Result
- **Result**: :white_check_mark: OK
- Triggered by @zxkane on `pull_request`

| Metric | Status | Value | Error Threshold |
|:------:|:------:|:-----:|:---------------:|
|Reliability rating|:white_check_mark: OK|1|> 1|
|Security rating|:white_check_mark: OK|1|> 1|
|Sqale rating|:white_check_mark: OK|1|> 1|
|Coverage|:white_check_mark: OK|83.40|< 80|
|Duplicated lines density|:white_check_mark: OK|5.60|> 30|
|Blocker violations|:white_check_mark: OK|0|> 0|
|Bugs|:white_check_mark: OK|0|> 0|
|Code smells|:white_check_mark: OK|2|> 40|
|Critical violations|:white_check_mark: OK|0|> 0|
|Major violations|:white_check_mark: OK|0|> 0|
|Vulnerabilities|:white_check_mark: OK|0|> 0|

[View on SonarQube](http://sonarqube:9000/dashboard?id=pr-1386)
###### _updated: 5/26/2024, 08:38:37 (UTC+0)_

2024-05-26 08:38 UTC, zxkane commented
# SonarQube Code Analytics
## Quality Gate passed

![passed](https://hsonar.s3.ap-southeast-1.amazonaws.com/images/passed.png)

## Additional information
*The following metrics might not affect the Quality Gate status but improving them will improve your project code quality.*

## Issues
![bug](https://hsonar.s3.ap-southeast-1.amazonaws.com/images/bug.png)   [0 Bugs](http://sonarqube:9000/project/issues?id=pr-1386&resolved=false&sinceLeakPeriod=true&types=BUG)

![vulnerability](https://hsonar.s3.ap-southeast-1.amazonaws.com/images/vulnerability.png)   [0 Vulnerabilities](http://sonarqube:9000/project/issues?id=pr-1386&resolved=false&sinceLeakPeriod=true&types=VULNERABILITY)

![code_smell](https://hsonar.s3.ap-southeast-1.amazonaws.com/images/code_smell.png)   [0 Code Smells](http://sonarqube:9000/project/issues?id=pr-1386&resolved=false&sinceLeakPeriod=true&types=CODE_SMELL)

## Coverage and Duplications
*No data* **Coverage**

*No data* **Duplication**

2024-05-27 01:26 UTC, llmin submitted a review, later dismissed

2024-05-27 01:55 UTC, zxkane commented
### SonarQube Quality Gate Result
- **Result**: :white_check_mark: OK
- Triggered by @zxkane on `pull_request`

| Metric | Status | Value | Error Threshold |
|:------:|:------:|:-----:|:---------------:|
|Reliability rating|:white_check_mark: OK|1|> 1|
|Security rating|:white_check_mark: OK|1|> 1|
|Sqale rating|:white_check_mark: OK|1|> 1|
|Coverage|:white_check_mark: OK|83.50|< 80|
|Duplicated lines density|:white_check_mark: OK|5.60|> 30|
|Blocker violations|:white_check_mark: OK|0|> 0|
|Bugs|:white_check_mark: OK|0|> 0|
|Code smells|:white_check_mark: OK|2|> 40|
|Critical violations|:white_check_mark: OK|0|> 0|
|Major violations|:white_check_mark: OK|0|> 0|
|Vulnerabilities|:white_check_mark: OK|0|> 0|

[View on SonarQube](http://sonarqube:9000/dashboard?id=pr-1386)
###### _updated: 5/27/2024, 01:55:35 (UTC+0)_

2024-05-27 02:48 UTC, luorobin-a2z commented on docs/en/upgrade.md
> +        If new events come before completing this step or the volume of migrated data is large, it is recommended to refresh the `clickstream_event_base_view` in batches. That is, based on the occurr
It is recommended to refresh the clickstream_event_base_view in batches, especially in the following scenarios:
- When there are new event load jobs coming in before the migration job completes.
- When the volume of migrated data is large (e.g., 100 millions in a batch).

Noe that refreshing the data in batches needs to be done based on the event timestamp. Call the following stored procedure multiple times, in order from old to new event timestamps.

2024-05-27 02:48 UTC, luorobin-a2z requested changes
refine the step 7 wording

2024-05-27 03:10 UTC, luorobin-a2z approved these changes

2024-05-27 03:35 UTC, zxkane commented
### SonarQube Quality Gate Result
- **Result**: :white_check_mark: OK
- Triggered by @zxkane on `pull_request`

| Metric | Status | Value | Error Threshold |
|:------:|:------:|:-----:|:---------------:|
|Reliability rating|:white_check_mark: OK|1|> 1|
|Security rating|:white_check_mark: OK|1|> 1|
|Sqale rating|:white_check_mark: OK|1|> 1|
|Coverage|:white_check_mark: OK|83.40|< 80|
|Duplicated lines density|:white_check_mark: OK|5.60|> 30|
|Blocker violations|:white_check_mark: OK|0|> 0|
|Bugs|:white_check_mark: OK|0|> 0|
|Code smells|:white_check_mark: OK|2|> 40|
|Critical violations|:white_check_mark: OK|0|> 0|
|Major violations|:white_check_mark: OK|0|> 0|
|Vulnerabilities|:white_check_mark: OK|0|> 0|

[View on SonarQube](http://sonarqube:9000/dashboard?id=pr-1386)
###### _updated: 5/27/2024, 03:35:12 (UTC+0)_

2024-05-27 03:45 UTC, merged