add docs for realtime and segments
awslabs/clickstream-analytics-on-aws pull request #1533
Opened 2024-07-12 09:37 UTC by luorobin-a2z

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

## Summary

(describe what this merge request does)

## Implementation highlights

(describe how the merge request does for feature changes, share the RFC link if it has)

## Test checklist

- [ ] add new test cases
- [ ] all code changes are covered by unit tests
- [ ] end-to-end tests
  - [ ] deploy web console with CloudFront + S3 + API gateway
  - [ ] deploy web console within VPC
  - [ ] deploy ingestion server
    - [ ] with MSK sink
    - [ ] with KDS sink
    - [ ] with S3 sink
  - [ ] deploy data processing
  - [ ] deploy data modeling
    - [ ] new Redshift Serverless
    - [ ] provisioned Redshift
    - [ ] Athena
  - [ ] deploy with reporting
  - [ ] streaming ingestion
    - [ ] with Redshift Serverless
    - [ ] with provisioned Redshift

## Is it a breaking change

- [ ] add parameters without default value in stack
- [ ] introduce new service permission in stack
- [ ] introduce new top level stack module

## Miscellaneous

- [ ] introduce new symbol link source file(s) to be shared among infra code, web console frontend, and web console backend

2024-07-12 10:07 UTC, zxkane commented
### SonarQube Quality Gate Result
- **Result**: :white_check_mark: OK
- Triggered by @luorobin-a2z on `pull_request`

| Metric | Status | Value | Error Threshold |
|:------:|:------:|:-----:|:---------------:|
|Reliability rating|:white_check_mark: OK|1|> 1|
|Security rating|:white_check_mark: OK|1|> 1|
|Sqale rating|:white_check_mark: OK|1|> 1|
|Coverage|:white_check_mark: OK|83.70|< 80|
|Duplicated lines density|:white_check_mark: OK|8.60|> 30|
|Blocker violations|:white_check_mark: OK|0|> 0|
|Bugs|:white_check_mark: OK|0|> 0|
|Code smells|:white_check_mark: OK|9|> 40|
|Critical violations|:white_check_mark: OK|0|> 0|
|Major violations|:white_check_mark: OK|0|> 0|
|Vulnerabilities|:white_check_mark: OK|0|> 0|

[View on SonarQube](http://sonarqube:9000/dashboard?id=pr-1533)
###### _updated: 7/12/2024, 10:07:18 (UTC+0)_

2024-07-12 10:07 UTC, zxkane commented
# SonarQube Code Analytics
## Quality Gate passed

![passed](https://hsonar.s3.ap-southeast-1.amazonaws.com/images/passed.png)

## Additional information
*The following metrics might not affect the Quality Gate status but improving them will improve your project code quality.*

## Issues
![bug](https://hsonar.s3.ap-southeast-1.amazonaws.com/images/bug.png)   [0 Bugs](http://sonarqube:9000/project/issues?id=pr-1533&resolved=false&sinceLeakPeriod=true&types=BUG)

![vulnerability](https://hsonar.s3.ap-southeast-1.amazonaws.com/images/vulnerability.png)   [0 Vulnerabilities](http://sonarqube:9000/project/issues?id=pr-1533&resolved=false&sinceLeakPeriod=true&types=VULNERABILITY)

![code_smell](https://hsonar.s3.ap-southeast-1.amazonaws.com/images/code_smell.png)   [0 Code Smells](http://sonarqube:9000/project/issues?id=pr-1533&resolved=false&sinceLeakPeriod=true&types=CODE_SMELL)

## Coverage and Duplications
*No data* **Coverage**

*No data* **Duplication**

2024-07-12 10:28 UTC, jingnanl commented on docs/en/analytics/realtime/index.md
> +You can start and stop the realtime data streaming by switching on and off the toggle to avoid unnecessary cost. In the backend, this option starts and stops the Flink application which process the c
process -> processes

2024-07-12 10:28 UTC, jingnanl commented on docs/en/analytics/segment/index.md
> +    - Manual - Segment will be refreshed when user manually trigger refresh
trigger -> triggers

2024-07-12 10:28 UTC, jingnanl commented on docs/en/analytics/segment/index.md
> +    - Automatically - Segment will be refreshed periodically. You can configure interval (e.g., Daily, Weekly, Monthly) and timing (e.g., 8AM).
Automatically -> Automatic
Also support custom cron or rate expression

2024-07-12 10:28 UTC, jingnanl commented on docs/en/analytics/segment/index.md
> +4. Specify a **Expirations settings**. If you specified Automatically as refresh method, you will need to set an expiration date for a segment after which the segment will stop auto refresh.
Automatically -> Automatic

Specify an Expiration settings.

Currently the expiration settings is not mandatory.

2024-07-12 10:28 UTC, jingnanl commented on docs/en/analytics/segment/index.md
> +|**User in segment/User in not segment**| Select users based on whether user belong to a segment or not.| Segments||
User not in segment

2024-07-15 03:52 UTC, zxkane commented
### SonarQube Quality Gate Result
- **Result**: :white_check_mark: OK
- Triggered by @luorobin-a2z on `pull_request`

| Metric | Status | Value | Error Threshold |
|:------:|:------:|:-----:|:---------------:|
|Reliability rating|:white_check_mark: OK|1|> 1|
|Security rating|:white_check_mark: OK|1|> 1|
|Sqale rating|:white_check_mark: OK|1|> 1|
|Coverage|:white_check_mark: OK|83.70|< 80|
|Duplicated lines density|:white_check_mark: OK|8.60|> 30|
|Blocker violations|:white_check_mark: OK|0|> 0|
|Bugs|:white_check_mark: OK|0|> 0|
|Code smells|:white_check_mark: OK|9|> 40|
|Critical violations|:white_check_mark: OK|0|> 0|
|Major violations|:white_check_mark: OK|0|> 0|
|Vulnerabilities|:white_check_mark: OK|0|> 0|

[View on SonarQube](http://sonarqube:9000/dashboard?id=pr-1533)
###### _updated: 7/15/2024, 03:52:37 (UTC+0)_

2024-07-15 03:52 UTC, zxkane commented
### SonarQube Quality Gate Result
- **Result**: :white_check_mark: OK
- Triggered by @luorobin-a2z on `pull_request`

| Metric | Status | Value | Error Threshold |
|:------:|:------:|:-----:|:---------------:|
|Reliability rating|:white_check_mark: OK|1|> 1|
|Security rating|:white_check_mark: OK|1|> 1|
|Sqale rating|:white_check_mark: OK|1|> 1|
|Coverage|:white_check_mark: OK|83.70|< 80|
|Duplicated lines density|:white_check_mark: OK|8.60|> 30|
|Blocker violations|:white_check_mark: OK|0|> 0|
|Bugs|:white_check_mark: OK|0|> 0|
|Code smells|:white_check_mark: OK|9|> 40|
|Critical violations|:white_check_mark: OK|0|> 0|
|Major violations|:white_check_mark: OK|0|> 0|
|Vulnerabilities|:white_check_mark: OK|0|> 0|

[View on SonarQube](http://sonarqube:9000/dashboard?id=pr-1533)
###### _updated: 7/15/2024, 03:52:57 (UTC+0)_

2024-07-15 15:36 UTC, zxkane commented
### SonarQube Quality Gate Result
- **Result**: :white_check_mark: OK
- Triggered by @zxkane on `pull_request`

| Metric | Status | Value | Error Threshold |
|:------:|:------:|:-----:|:---------------:|
|Reliability rating|:white_check_mark: OK|1|> 1|
|Security rating|:white_check_mark: OK|1|> 1|
|Sqale rating|:white_check_mark: OK|1|> 1|
|Coverage|:white_check_mark: OK|83.80|< 80|
|Duplicated lines density|:white_check_mark: OK|8.60|> 30|
|Blocker violations|:white_check_mark: OK|0|> 0|
|Bugs|:white_check_mark: OK|0|> 0|
|Code smells|:white_check_mark: OK|9|> 40|
|Critical violations|:white_check_mark: OK|0|> 0|
|Major violations|:white_check_mark: OK|0|> 0|
|Vulnerabilities|:white_check_mark: OK|0|> 0|

[View on SonarQube](http://sonarqube:9000/dashboard?id=pr-1533)
###### _updated: 7/15/2024, 15:36:49 (UTC+0)_

2024-07-16 02:35 UTC, zxkane requested changes
- [x] WARNING -  Doc file 'analytics/index.md' contains a relative link './segments/index.md', but the target 'analytics/segments/index.md' is not found among documentation files.

2024-07-16 03:20 UTC, zxkane requested changes
- [ ] miss the steps to enable/disable the stream at application level

2024-07-16 03:20 UTC, zxkane commented on docs/en/analytics/index.md
> +- [Segments](./segments/index.md). Create user segments.
`./segment/index.md`

2024-07-17 09:01 UTC, zxkane commented
### SonarQube Quality Gate Result
- **Result**: :white_check_mark: OK
- Triggered by @luorobin-a2z on `pull_request`

| Metric | Status | Value | Error Threshold |
|:------:|:------:|:-----:|:---------------:|
|Reliability rating|:white_check_mark: OK|1|> 1|
|Security rating|:white_check_mark: OK|1|> 1|
|Sqale rating|:white_check_mark: OK|1|> 1|
|Coverage|:white_check_mark: OK|83.80|< 80|
|Duplicated lines density|:white_check_mark: OK|8.60|> 30|
|Blocker violations|:white_check_mark: OK|0|> 0|
|Bugs|:white_check_mark: OK|0|> 0|
|Code smells|:white_check_mark: OK|9|> 40|
|Critical violations|:white_check_mark: OK|0|> 0|
|Major violations|:white_check_mark: OK|0|> 0|
|Vulnerabilities|:white_check_mark: OK|0|> 0|

[View on SonarQube](http://sonarqube:9000/dashboard?id=pr-1533)
###### _updated: 7/17/2024, 09:01:04 (UTC+0)_

2024-07-20 00:18 UTC, zxkane approved these changes

2024-07-20 00:51 UTC, merged