docs: add streaming cost in doc
awslabs/clickstream-analytics-on-aws pull request #1560
Opened 2024-07-30 08:22 UTC by dengmingtong

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

## Summary

add streaming cost in doc

<img width="1070" alt="Screenshot 2024-07-30 at 16 20 25" src="https://github.com/user-attachments/assets/5e75f1cf-def8-4daa-962e-478cdbbb69cf">

<img width="1200" alt="Screenshot 2024-07-30 at 16 19 54" src="https://github.com/user-attachments/assets/4e5d8dc9-27a9-47c5-84b4-ddd0a135cd45">

## Implementation highlights

(describe how the merge request does for feature changes, share the RFC link if it has)

## Test checklist

- [ ] add new test cases
- [ ] all code changes are covered by unit tests
- [ ] end-to-end tests
  - [ ] deploy web console with CloudFront + S3 + API gateway
  - [ ] deploy web console within VPC
  - [ ] deploy ingestion server
    - [ ] with MSK sink
    - [ ] with KDS sink
    - [ ] with S3 sink
  - [ ] deploy data processing
  - [ ] deploy data modeling
    - [ ] new Redshift Serverless
    - [ ] provisioned Redshift
    - [ ] Athena
  - [ ] deploy with reporting
  - [ ] streaming ingestion
    - [ ] with Redshift Serverless
    - [ ] with provisioned Redshift

## Is it a breaking change

- [ ] add parameters without default value in stack
- [ ] introduce new service permission in stack
- [ ] introduce new top level stack module

## Miscellaneous

- [ ] introduce new symbol link source file(s) to be shared among infra code, web console frontend, and web console backend

2024-07-30 08:52 UTC, aws-solution-clickstream-analytics commented
### SonarQube Quality Gate Result
- **Result**: :white_check_mark: OK
- Triggered by @dengmingtong on `pull_request`

| Metric | Status | Value | Error Threshold |
|:------:|:------:|:-----:|:---------------:|
|Reliability rating|:white_check_mark: OK|1|> 1|
|Security rating|:white_check_mark: OK|1|> 1|
|Sqale rating|:white_check_mark: OK|1|> 1|
|Coverage|:white_check_mark: OK|83.80|< 80|
|Duplicated lines density|:white_check_mark: OK|8.50|> 30|
|Blocker violations|:white_check_mark: OK|0|> 0|
|Bugs|:white_check_mark: OK|0|> 0|
|Code smells|:white_check_mark: OK|10|> 40|
|Critical violations|:white_check_mark: OK|0|> 0|
|Major violations|:white_check_mark: OK|0|> 0|
|Vulnerabilities|:white_check_mark: OK|0|> 0|

[View on SonarQube](http://sonarqube:9000/dashboard?id=pr-1560)
###### _updated: 7/30/2024, 08:52:25 (UTC+0)_

2024-07-30 08:52 UTC, aws-solution-clickstream-analytics commented
# SonarQube Code Analytics
## Quality Gate passed

![passed](https://hsonar.s3.ap-southeast-1.amazonaws.com/images/passed.png)

## Additional information
*The following metrics might not affect the Quality Gate status but improving them will improve your project code quality.*

## Issues
![bug](https://hsonar.s3.ap-southeast-1.amazonaws.com/images/bug.png)   [0 Bugs](http://sonarqube:9000/project/issues?id=pr-1560&resolved=false&sinceLeakPeriod=true&types=BUG)

![vulnerability](https://hsonar.s3.ap-southeast-1.amazonaws.com/images/vulnerability.png)   [0 Vulnerabilities](http://sonarqube:9000/project/issues?id=pr-1560&resolved=false&sinceLeakPeriod=true&types=VULNERABILITY)

![code_smell](https://hsonar.s3.ap-southeast-1.amazonaws.com/images/code_smell.png)   [0 Code Smells](http://sonarqube:9000/project/issues?id=pr-1560&resolved=false&sinceLeakPeriod=true&types=CODE_SMELL)

## Coverage and Duplications
*No data* **Coverage**

*No data* **Duplication**

2024-07-31 03:13 UTC, zxkane requested changes

2024-07-31 03:13 UTC, zxkane commented on docs/en/plan-deployment/cost.md
> +Key assumptions include:
need new line?

2024-07-31 03:13 UTC, zxkane commented on docs/en/plan-deployment/cost.md
> +## Realtime streaming mode
change to `Streaming mode`

2024-07-31 03:13 UTC, zxkane commented on docs/en/plan-deployment/cost.md
> +- For 10/100 RPS, the batch EMR schedule interval is daily
add a assumption: only one application

2024-07-31 05:56 UTC, luorobin-a2z approved these changes

2024-07-31 07:00 UTC, aws-solution-clickstream-analytics commented
### SonarQube Quality Gate Result
- **Result**: :white_check_mark: OK
- Triggered by @dengmingtong on `pull_request`

| Metric | Status | Value | Error Threshold |
|:------:|:------:|:-----:|:---------------:|
|Reliability rating|:white_check_mark: OK|1|> 1|
|Security rating|:white_check_mark: OK|1|> 1|
|Sqale rating|:white_check_mark: OK|1|> 1|
|Coverage|:white_check_mark: OK|83.70|< 80|
|Duplicated lines density|:white_check_mark: OK|8.50|> 30|
|Blocker violations|:white_check_mark: OK|0|> 0|
|Bugs|:white_check_mark: OK|0|> 0|
|Code smells|:white_check_mark: OK|10|> 40|
|Critical violations|:white_check_mark: OK|0|> 0|
|Major violations|:white_check_mark: OK|0|> 0|
|Vulnerabilities|:white_check_mark: OK|0|> 0|

[View on SonarQube](http://sonarqube:9000/dashboard?id=pr-1560)
###### _updated: 7/31/2024, 07:00:18 (UTC+0)_

2024-08-01 01:40 UTC, zxkane requested changes

2024-08-01 01:40 UTC, zxkane commented on docs/en/plan-deployment/cost.md
> +| 1000RPS             | 1 Hour                |    $1189    | Serverless (16 based RPU) |   $75       |  $24     |   $1288   |
Should be total Redshift cost(for batching and streaming)

2024-08-01 01:40 UTC, zxkane commented on docs/en/plan-deployment/cost.md
> +| Request Per Second | Daily enable real-time duration |  Kinesis (On-Demand) | Redshift type     | Redshift cost  | Managed Apache Flink | Additional Total (USD/Month) |
Additional Total -> Total

2024-08-01 01:40 UTC, zxkane commented on docs/en/plan-deployment/cost.md
> +    - If streaming is enabled 24 hours a day, provisioning redshift is more economical.
Provisioned Redshift

2024-08-01 01:40 UTC, zxkane commented on docs/en/plan-deployment/cost.md
> +    - Kinesis (On-Demand) cost include ingestion Kinesis cost.
-> Kinesis (On-Demand) costs include KDS used by the Ingestion module

2024-08-01 03:45 UTC, aws-solution-clickstream-analytics commented
### SonarQube Quality Gate Result
- **Result**: :white_check_mark: OK
- Triggered by @dengmingtong on `pull_request`

| Metric | Status | Value | Error Threshold |
|:------:|:------:|:-----:|:---------------:|
|Reliability rating|:white_check_mark: OK|1|> 1|
|Security rating|:white_check_mark: OK|1|> 1|
|Sqale rating|:white_check_mark: OK|1|> 1|
|Coverage|:white_check_mark: OK|83.70|< 80|
|Duplicated lines density|:white_check_mark: OK|8.50|> 30|
|Blocker violations|:white_check_mark: OK|0|> 0|
|Bugs|:white_check_mark: OK|0|> 0|
|Code smells|:white_check_mark: OK|10|> 40|
|Critical violations|:white_check_mark: OK|0|> 0|
|Major violations|:white_check_mark: OK|0|> 0|
|Vulnerabilities|:white_check_mark: OK|0|> 0|

[View on SonarQube](http://sonarqube:9000/dashboard?id=pr-1560)
###### _updated: 8/1/2024, 03:45:35 (UTC+0)_

2024-08-01 05:44 UTC, zxkane approved these changes

2024-08-01 06:10 UTC, aws-solution-clickstream-analytics commented
### SonarQube Quality Gate Result
- **Result**: :white_check_mark: OK
- Triggered by @dengmingtong on `pull_request`

| Metric | Status | Value | Error Threshold |
|:------:|:------:|:-----:|:---------------:|
|Reliability rating|:white_check_mark: OK|1|> 1|
|Security rating|:white_check_mark: OK|1|> 1|
|Sqale rating|:white_check_mark: OK|1|> 1|
|Coverage|:white_check_mark: OK|83.70|< 80|
|Duplicated lines density|:white_check_mark: OK|8.50|> 30|
|Blocker violations|:white_check_mark: OK|0|> 0|
|Bugs|:white_check_mark: OK|0|> 0|
|Code smells|:white_check_mark: OK|10|> 40|
|Critical violations|:white_check_mark: OK|0|> 0|
|Major violations|:white_check_mark: OK|0|> 0|
|Vulnerabilities|:white_check_mark: OK|0|> 0|

[View on SonarQube](http://sonarqube:9000/dashboard?id=pr-1560)
###### _updated: 8/1/2024, 06:10:46 (UTC+0)_

2024-08-01 06:46 UTC, merged