fix: update CORS pattern
awslabs/clickstream-analytics-on-aws pull request #158
Opened 2023-08-23 05:34 UTC by tyyzqmf

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

## Summary

closes: #127 

## Implementation highlights

(describe how the merge request does for feature changes, share the RFC link if it has)

## Test checklist

- [ ] add new test cases
- [ ] all code changes are covered by unit tests
- [ ] end-to-end tests
  - [ ] deploy web console with CloudFront + S3 + API gateway
  - [ ] deploy web console within VPC
  - [ ] deploy ingestion server
    - [ ] with MSK sink
    - [ ] with KDS sink
    - [ ] with S3 sink
  - [ ] deploy data processing
  - [ ] deploy data modeling
    - [ ] new Redshift Serverless
    - [ ] provisioned Redshift
    - [ ] Athena
  - [ ] deploy with reporting

## Is it a breaking change

- [ ] add parameters without default value in stack
- [ ] introduce new service permission in stack
- [ ] introduce new top level stack module

## Miscellaneous

- [ ] introduce new symbol link source file(s) to be shared among infra code, web console frontend, and web console backend

2023-08-23 08:38 UTC, zxkane requested changes

2023-08-23 08:38 UTC, zxkane commented on src/control-plane/backend/lambda/api/test/api/utils.test.ts
> +    const invalidValues = [
add an invalid case `*,abc.com`

2023-08-23 08:44 UTC, tyyzqmf commented on src/control-plane/backend/lambda/api/test/api/utils.test.ts
> +    const invalidValues = [
done

2023-08-25 15:46 UTC, zxkane requested changes
Also, correct the hint example in web console.

<img width="784" alt="image" src="https://github.com/awslabs/clickstream-analytics-on-aws/assets/843303/0973b3c4-0c41-432a-8825-148791b43cd1">

2023-08-25 15:50 UTC, zxkane commented
> Also, correct the hint example in web console.
> 
> <img alt="image" width="784" src="https://user-images.githubusercontent.com/843303/263321120-0973b3c4-0c41-432a-8825-148791b43cd1.png">

@luorobin-a2z how about updating the description of CORS setting to `Enable web requests from specific domains by specifying them in the provided textbox. By default, the ingestion server's CORS origin is empty to disable CORS requests.`?

2023-08-28 04:01 UTC, luorobin-a2z commented
Please move CORS setting to above the "additional settings"
Update CORS description as below:
CORS setting allows requests from specific domains to be sent by browsers. This is critical if you are collecting clickstream data from a web application, please input the allowed domain(s) in the following box.

2023-08-28 06:36 UTC, zxkane approved these changes

2023-08-28 07:23 UTC, merged