feat: event explore
awslabs/clickstream-analytics-on-aws pull request #178
Opened 2023-08-29 05:51 UTC by tyyzqmf

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

## Summary

(describe what this merge request does)

## Implementation highlights

(describe how the merge request does for feature changes, share the RFC link if it has)

## Test checklist

- [ ] add new test cases
- [ ] all code changes are covered by unit tests
- [ ] end-to-end tests
  - [ ] deploy web console with CloudFront + S3 + API gateway
  - [ ] deploy web console within VPC
  - [ ] deploy ingestion server
    - [ ] with MSK sink
    - [ ] with KDS sink
    - [ ] with S3 sink
  - [ ] deploy data processing
  - [ ] deploy data modeling
    - [ ] new Redshift Serverless
    - [ ] provisioned Redshift
    - [ ] Athena
  - [ ] deploy with reporting

## Is it a breaking change

- [ ] add parameters without default value in stack
- [ ] introduce new service permission in stack
- [ ] introduce new top level stack module

## Miscellaneous

- [ ] introduce new symbol link source file(s) to be shared among infra code, web console frontend, and web console backend

2023-08-30 00:15 UTC, zxkane requested changes

2023-08-30 00:15 UTC, zxkane commented on frontend/src/components/layouts/Navigation.tsx
> +    //   href: `/analytics/${projectId}/app/${appId}/realtime`,
Will enable those links?

2023-08-30 12:56 UTC, tyyzqmf commented on frontend/src/components/layouts/Navigation.tsx
> +    //   href: `/analytics/${projectId}/app/${appId}/realtime`,
wait pipeline realtime

2023-08-30 14:16 UTC, chenhaiyun commented on frontend/src/pages/analytics/event/AnalyticsEvent.tsx
> +                          {t('analytics:button.reset')}
move to: `common.button.reset`

2023-08-30 14:16 UTC, chenhaiyun commented on frontend/src/pages/analytics/event/AnalyticsEvent.tsx
> +                          {t('analytics:button.save')}
move to `common.button.save`

2023-08-30 14:16 UTC, chenhaiyun commented on frontend/src/pages/analytics/event/AnalyticsEvent.tsx
> +                  {t('common:button.preview')}
common is default. we can use `button.preview` directly

2023-08-31 06:32 UTC, zxkane approved these changes

2023-08-31 06:32 UTC, merged