feat: add sql builder for funnel chart
awslabs/clickstream-analytics-on-aws pull request #19
Opened 2023-07-11 06:11 UTC by llmin

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

## Summary

(describe what this merge request does)

## Implementation highlights

(describe how the merge request does for feature changes, share the RFC link if it has)

## Test checklist

- [x] add new test cases
- [ ] all code changes are covered by unit tests
- [ ] end-to-end tests
  - [ ] deploy control plane with CloudFront + S3 + API gateway
  - [ ] deploy control plane within VPC
  - [ ] deploy ingestion server
    - [ ] with MSK sink
    - [ ] with KDS sink
    - [ ] with S3 sink
  - [ ] deploy data processing
  - [ ] deploy data modeling
    - [ ] new Redshift Serverless
    - [ ] provisioned Redshift
    - [ ] Athena
  - [ ] deploy with reporting

## Is it a breaking change

- [ ] add parameters without default value in stack
- [ ] introduce new service permission in stack
- [ ] introduce new top level stack module

2023-07-13 04:21 UTC, zxkane requested changes

2023-07-13 04:21 UTC, zxkane commented on src/control-plane/backend/lambda/api/common/sql-builder.ts
> +  eventsNames: string[];
support filtering with event attributes too

2023-07-13 08:54 UTC, tyyzqmf approved these changes

2023-07-18 03:12 UTC, zxkane approved these changes

2023-07-18 10:30 UTC, merged