docs: update swift sdk
awslabs/clickstream-analytics-on-aws pull request #214
Opened 2023-09-11 06:13 UTC by zhu-xiaowei

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

## Summary
1. add the screen view definition
2. update the definition of session
3. update the definition of user engagement
4. update the example event for record an event
5. add the data type for each attribute
6. add reference link
7. adjust the content structure
8. update the error code
9. fix typo

## Implementation highlights

(describe how the merge request does for feature changes, share the RFC link if it has)

## Test checklist

- [ ] add new test cases
- [ ] all code changes are covered by unit tests
- [ ] end-to-end tests
  - [ ] deploy web console with CloudFront + S3 + API gateway
  - [ ] deploy web console within VPC
  - [ ] deploy ingestion server
    - [ ] with MSK sink
    - [ ] with KDS sink
    - [ ] with S3 sink
  - [ ] deploy data processing
  - [ ] deploy data modeling
    - [ ] new Redshift Serverless
    - [ ] provisioned Redshift
    - [ ] Athena
  - [ ] deploy with reporting

## Is it a breaking change

- [ ] add parameters without default value in stack
- [ ] introduce new service permission in stack
- [ ] introduce new top level stack module

## Miscellaneous

- [ ] introduce new symbol link source file(s) to be shared among infra code, web console frontend, and web console backend

2023-09-11 15:33 UTC, zxkane requested changes

2023-09-11 15:33 UTC, zxkane commented on docs/en/sdk-manual/swift.md
> +Clickstream requires Xcode 13.4 or higher to build.
add `Swift SDK`

2023-09-11 16:02 UTC, zxkane requested changes

2023-09-11 16:02 UTC, zxkane commented on docs/en/sdk-manual/swift.md
> +		    "_screen_unique_id": "5260751568"
indentation is wrong

2023-09-12 01:10 UTC, zhu-xiaowei commented on docs/en/sdk-manual/swift.md
> +Clickstream requires Xcode 13.4 or higher to build.
added

2023-09-12 01:12 UTC, zhu-xiaowei commented on docs/en/sdk-manual/swift.md
> +    ```
removed

2023-09-12 01:13 UTC, zhu-xiaowei commented on docs/en/sdk-manual/swift.md
>  3. The event name and attribute name are in case-sensitive, So the event `Add_to_cart` and `add_to_cart` will be Recognized as two different event.
fixed

2023-09-12 01:14 UTC, zhu-xiaowei commented on docs/en/sdk-manual/swift.md
> +		    "_screen_unique_id": "5260751568"
fixed

2023-09-12 01:43 UTC, zxkane approved these changes

2023-09-12 02:40 UTC, merged