feat: aggregating multiday metadata and patch display info before api return
awslabs/clickstream-analytics-on-aws pull request #218
Opened 2023-09-12 14:27 UTC by tyyzqmf

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

## Summary

(describe what this merge request does)

## Implementation highlights

(describe how the merge request does for feature changes, share the RFC link if it has)

## Test checklist

- [ ] add new test cases
- [ ] all code changes are covered by unit tests
- [ ] end-to-end tests
  - [ ] deploy web console with CloudFront + S3 + API gateway
  - [ ] deploy web console within VPC
  - [ ] deploy ingestion server
    - [ ] with MSK sink
    - [ ] with KDS sink
    - [ ] with S3 sink
  - [ ] deploy data processing
  - [ ] deploy data modeling
    - [ ] new Redshift Serverless
    - [ ] provisioned Redshift
    - [ ] Athena
  - [ ] deploy with reporting

## Is it a breaking change

- [ ] add parameters without default value in stack
- [ ] introduce new service permission in stack
- [ ] introduce new top level stack module

## Miscellaneous

- [ ] introduce new symbol link source file(s) to be shared among infra code, web console frontend, and web console backend

2023-09-13 03:36 UTC, zxkane requested changes

2023-09-13 03:36 UTC, zxkane commented on src/control-plane/backend/click-stream-api.ts
> +    const analyticsDisplayTable = new Table(this, 'ClickstreamAnalyticsDisplay', {
Could we share the table Meta?

2023-09-13 06:55 UTC, tyyzqmf commented on src/control-plane/backend/click-stream-api.ts
> +    const analyticsDisplayTable = new Table(this, 'ClickstreamAnalyticsDisplay', {
moved display data to metadata table

2023-09-14 06:57 UTC, chenhaiyun commented on frontend/public/locales/zh/analytics.json
>          "tableLoading": "加载中",
Duplicated with line 106 and 107?

2023-09-14 06:57 UTC, chenhaiyun commented on frontend/src/pages/analytics/metadata/table/MetadataDictionaryTable.tsx
> +          throw new Error(message);
Change to `alertMsg`?

2023-09-14 06:57 UTC, chenhaiyun commented on frontend/src/pages/analytics/metadata/user-attributes/MetadataUserAttributeSplitPanel.tsx
> +        id: `USER_ATTRIBUTE#${attributeDetails.id}`,
move `USER_ATTRIBUTE`  as a constant

2023-09-14 06:57 UTC, chenhaiyun commented on frontend/src/pages/analytics/metadata/user-attributes/MetadataUserAttributes.tsx
> +          id: `USER_ATTRIBUTE#${newItem.id}`,
`USER_ATTRIBUTE` as a constant

2023-09-14 06:57 UTC, chenhaiyun commented on frontend/src/pages/analytics/path/AnalyticsPath.tsx
> +    return [];
Why add this line?

2023-09-15 02:36 UTC, tyyzqmf commented on frontend/src/pages/analytics/path/AnalyticsPath.tsx
> +    return [];
removed

2023-09-15 03:13 UTC, zxkane approved these changes

2023-09-15 03:35 UTC, merged