chore: suppress vpc warnings
awslabs/clickstream-analytics-on-aws pull request #22
Opened 2023-07-11 10:16 UTC by llmin

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

## Summary

closes #11 

## Implementation highlights

(describe how the merge request does for feature changes, share the RFC link if it has)

## Test checklist

- [ ] add new test cases
- [ ] all code changes are covered by unit tests
- [ ] end-to-end tests
  - [ ] deploy control plane with CloudFront + S3 + API gateway
  - [x] deploy control plane within VPC
  - [ ] deploy ingestion server
    - [ ] with MSK sink
    - [ ] with KDS sink
    - [ ] with S3 sink
  - [ ] deploy data processing
  - [ ] deploy data modeling
    - [ ] new Redshift Serverless
    - [ ] provisioned Redshift
    - [ ] Athena
  - [ ] deploy with reporting

## Is it a breaking change

- [ ] add parameters without default value in stack
- [ ] introduce new service permission in stack
- [ ] introduce new top level stack module

2023-07-11 10:20 UTC, llmin commented
@amliuyong @dengmingtong @qiaow02 Would you please help to do test for this change? (deploy your own part stack locally)

2023-07-20 01:40 UTC, zxkane requested changes

2023-07-20 01:40 UTC, zxkane commented on src/common/vpc-utils.ts
> +  if (publicSubnet1 !== undefined) {
could we specify a fake route id when importing the vpc? It should be fine we don’t use the route info.

2023-07-21 05:45 UTC, zxkane requested changes

2023-07-21 05:45 UTC, zxkane commented on src/common/vpc-utils.ts
> +  vpcId: string;
add `readonly` modifier

2023-07-21 14:37 UTC, zxkane approved these changes

2023-07-21 14:37 UTC, merged