fix: add analytics metadata DDB table Arn parameter to Redshift stack
awslabs/clickstream-analytics-on-aws pull request #255
Opened 2023-09-26 11:20 UTC by tyyzqmf

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

## Summary

(describe what this merge request does)

## Implementation highlights

(describe how the merge request does for feature changes, share the RFC link if it has)

## Test checklist

- [ ] add new test cases
- [ ] all code changes are covered by unit tests
- [ ] end-to-end tests
  - [ ] deploy web console with CloudFront + S3 + API gateway
  - [ ] deploy web console within VPC
  - [ ] deploy ingestion server
    - [ ] with MSK sink
    - [ ] with KDS sink
    - [ ] with S3 sink
  - [ ] deploy data processing
  - [ ] deploy data modeling
    - [ ] new Redshift Serverless
    - [ ] provisioned Redshift
    - [ ] Athena
  - [ ] deploy with reporting

## Is it a breaking change

- [ ] add parameters without default value in stack
- [ ] introduce new service permission in stack
- [ ] introduce new top level stack module

## Miscellaneous

- [ ] introduce new symbol link source file(s) to be shared among infra code, web console frontend, and web console backend

2023-09-26 15:42 UTC, zxkane requested changes

2023-09-26 15:42 UTC, zxkane commented on test/jestEnv.js
> +process.env.AWS_ACCOUNT_ID = '555555555555'
add it to allowed list

https://github.com/awslabs/clickstream-analytics-on-aws/blob/main/.gitallowed

2023-09-27 01:49 UTC, zxkane approved these changes

2023-09-27 03:32 UTC, dengmingtong approved these changes

2023-09-27 03:32 UTC, merged