docs: correct field name
awslabs/clickstream-analytics-on-aws pull request #277
Opened 2023-10-07 07:27 UTC by techeditor

correct field name

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

## Summary

(describe what this merge request does)

## Implementation highlights

(describe how the merge request does for feature changes, share the RFC link if it has)

## Test checklist

- [ ] add new test cases
- [ ] all code changes are covered by unit tests
- [ ] end-to-end tests
  - [ ] deploy web console with CloudFront + S3 + API gateway
  - [ ] deploy web console within VPC
  - [ ] deploy ingestion server
    - [ ] with MSK sink
    - [ ] with KDS sink
    - [ ] with S3 sink
  - [ ] deploy data processing
  - [ ] deploy data modeling
    - [ ] new Redshift Serverless
    - [ ] provisioned Redshift
    - [ ] Athena
  - [ ] deploy with reporting

## Is it a breaking change

- [ ] add parameters without default value in stack
- [ ] introduce new service permission in stack
- [ ] introduce new top level stack module

## Miscellaneous

- [ ] introduce new symbol link source file(s) to be shared among infra code, web console frontend, and web console backend

2023-10-07 09:06 UTC, luorobin-a2z approved these changes

2023-10-07 09:09 UTC, zxkane requested changes

2023-10-07 09:09 UTC, zxkane commented on docs/zh/pipeline-mgmt/data-processing/data-schema.md
> +| user_ltv.currency  | DOUBLE PRECISION               | FLOAT| 用户的生命周期价值（货币）。 |
We need update the en version too.

2023-10-07 14:03 UTC, zxkane approved these changes

2023-10-08 03:04 UTC, zxkane approved these changes

2023-10-08 10:23 UTC, luorobin-a2z approved these changes

2023-10-08 10:23 UTC, merged