feat: show built-in metadata when no data in DDB
awslabs/clickstream-analytics-on-aws pull request #355
Opened 2023-10-24 09:34 UTC by tyyzqmf

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

## Summary

(describe what this merge request does)

## Implementation highlights

(describe how the merge request does for feature changes, share the RFC link if it has)

## Test checklist

- [ ] add new test cases
- [ ] all code changes are covered by unit tests
- [ ] end-to-end tests
  - [ ] deploy web console with CloudFront + S3 + API gateway
  - [ ] deploy web console within VPC
  - [ ] deploy ingestion server
    - [ ] with MSK sink
    - [ ] with KDS sink
    - [ ] with S3 sink
  - [ ] deploy data processing
  - [ ] deploy data modeling
    - [ ] new Redshift Serverless
    - [ ] provisioned Redshift
    - [ ] Athena
  - [ ] deploy with reporting

## Is it a breaking change

- [ ] add parameters without default value in stack
- [ ] introduce new service permission in stack
- [ ] introduce new top level stack module

## Miscellaneous

- [ ] introduce new symbol link source file(s) to be shared among infra code, web console frontend, and web console backend

2023-10-24 15:10 UTC, zxkane requested changes

2023-10-25 02:27 UTC, tyyzqmf commented on src/control-plane/backend/lambda/api/common/utils.ts
> +    // Add built-in metadata
This is an invalid comment.

2023-10-25 02:52 UTC, tyyzqmf commented on src/control-plane/backend/lambda/api/store/dynamodb/dynamodb-metadata-store.ts
> +            id: `${projectId}#${appId}#${e.name}#${preset.name}#${preset.dataType}`,
fix it in other pr

2023-10-25 05:21 UTC, zxkane approved these changes

2023-10-25 05:21 UTC, merged