drat: refactor load data workflow
awslabs/clickstream-analytics-on-aws pull request #361
Opened 2023-10-25 08:23 UTC by amliuyong

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

## Summary

(describe what this merge request does)

## Implementation highlights

(describe how the merge request does for feature changes, share the RFC link if it has)

## Test checklist

- [x] add new test cases
- [ ] all code changes are covered by unit tests
- [ ] end-to-end tests
  - [ ] deploy web console with CloudFront + S3 + API gateway
  - [ ] deploy web console within VPC
  - [ ] deploy ingestion server
    - [ ] with MSK sink
    - [ ] with KDS sink
    - [ ] with S3 sink
  - [ ] deploy data processing
  - [x] deploy data modeling
    - [x] new Redshift Serverless
    - [ ] provisioned Redshift
    - [ ] Athena
  - [ ] deploy with reporting

## Is it a breaking change

- [ ] add parameters without default value in stack
- [ ] introduce new service permission in stack
- [ ] introduce new top level stack module

## Miscellaneous

- [ ] introduce new symbol link source file(s) to be shared among infra code, web console frontend, and web console backend

2023-10-27 07:51 UTC, zxkane requested changes

2023-10-27 08:54 UTC, amliuyong commented on src/analytics/lambdas/load-data-workflow/has-more-job-new.ts
> +    const prefixQuery = odsEventBucketWithPrefix.replace(new RegExp(`\/${REDSHIFT_ODS_TABLE_NAME}\/?$`), `/${redshiftTableName}/`);
changed to `new RegExp(`/${REDSHIFT_ODS_TABLE_NAME}/?$`)`, 
"\/" is unnecessary.  
check the sonarqube checks.

2023-10-27 08:59 UTC, amliuyong commented on src/analytics/lambdas/load-data-workflow/create-load-manifest.ts
> +  let processingRecordResp = await queryItems(tableName, indexName, odsEventBucketWithPrefix, JobStatus.JOB_PROCESSING, undefined);
the step `Has Other Running Workflow` can make sure only one step function is in running state.
 
if we see JOB_PROCESSING files here, they are failed-loaded files by previous step function, here add them to candidate list and reprocess them.

2023-10-27 09:10 UTC, amliuyong commented on src/analytics/private/load-ods-data-workflow.ts
> +      const odsSource: ODSSource = (props.tablesOdsSource as any)[`${tableName}`];
changed to ```
const [tableName, odsSource] of Object.entries(props.tablesOdsSource)
```

2023-10-27 15:28 UTC, zxkane commented on src/analytics/lambdas/load-data-workflow/create-load-manifest.ts
> +  let processingRecordResp = await queryItems(tableName, indexName, odsEventBucketWithPrefix, JobStatus.JOB_PROCESSING, undefined);
What's your mechanism to exit the infinite loop if some files are unable to be loaded by Redshift? Do you have a way like DLQ to handle this case?

2023-10-30 01:44 UTC, amliuyong commented on src/analytics/lambdas/load-data-workflow/create-load-manifest.ts
> +  let processingRecordResp = await queryItems(tableName, indexName, odsEventBucketWithPrefix, JobStatus.JOB_PROCESSING, undefined);
If there are files in New or Processing status, the workflow will continue to run util loading them all. 
If files are unable to be loaded(e.g. bad files, wrong schema), the workflow will continue failing and exit, alarm will be raised. In this situation, we need to manually check.

2023-10-30 02:41 UTC, zxkane approved these changes

2023-10-30 02:41 UTC, merged