docs: add flutter sdk
awslabs/clickstream-analytics-on-aws pull request #399
Opened 2023-11-01 08:20 UTC by zhu-xiaowei

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

## Summary

1. add flutter SDK doc

## Implementation highlights

(describe how the merge request does for feature changes, share the RFC link if it has)

## Test checklist

- [ ] add new test cases
- [ ] all code changes are covered by unit tests
- [ ] end-to-end tests
  - [ ] deploy web console with CloudFront + S3 + API gateway
  - [ ] deploy web console within VPC
  - [ ] deploy ingestion server
    - [ ] with MSK sink
    - [ ] with KDS sink
    - [ ] with S3 sink
  - [ ] deploy data processing
  - [ ] deploy data modeling
    - [ ] new Redshift Serverless
    - [ ] provisioned Redshift
    - [ ] Athena
  - [ ] deploy with reporting

## Is it a breaking change

- [ ] add parameters without default value in stack
- [ ] introduce new service permission in stack
- [ ] introduce new top level stack module

## Miscellaneous

- [ ] introduce new symbol link source file(s) to be shared among infra code, web console frontend, and web console backend

2023-11-02 01:38 UTC, luorobin-a2z approved these changes
approve

2023-11-02 01:38 UTC, luorobin-a2z approved these changes

2023-11-30 06:27 UTC, zxkane requested changes

2023-11-30 06:27 UTC, zxkane commented on README.md
> +[http-api]: https://awslabs.github.io/clickstream-analytics-on-aws/en/sdk-manual/http-api/
update this link

2023-11-30 06:56 UTC, zhu-xiaowei commented on README.md
> +[http-api]: https://awslabs.github.io/clickstream-analytics-on-aws/en/sdk-manual/http-api/
fixed.

2023-11-30 07:24 UTC, zxkane approved these changes

2023-11-30 07:38 UTC, merged