chore: UI issues
awslabs/clickstream-analytics-on-aws pull request #508
Opened 2023-11-18 10:23 UTC by tyyzqmf

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

## Summary

1. display MSK refresh button
2. enforce at least 2 for the maximum for ingestion server
3. filter icon in Retention analysis
4. embed chart placehoder & increase create dashboard wait time
5. funnel default chart type is bar
6. delete path explore platform and fix node type data
7. auto receive value when input focus is removed from the input

## Implementation highlights

(describe how the merge request does for feature changes, share the RFC link if it has)

## Test checklist

- [ ] add new test cases
- [ ] all code changes are covered by unit tests
- [ ] end-to-end tests
  - [ ] deploy web console with CloudFront + S3 + API gateway
  - [ ] deploy web console within VPC
  - [ ] deploy ingestion server
    - [ ] with MSK sink
    - [ ] with KDS sink
    - [ ] with S3 sink
  - [ ] deploy data processing
  - [ ] deploy data modeling
    - [ ] new Redshift Serverless
    - [ ] provisioned Redshift
    - [ ] Athena
  - [ ] deploy with reporting

## Is it a breaking change

- [ ] add parameters without default value in stack
- [ ] introduce new service permission in stack
- [ ] introduce new top level stack module

## Miscellaneous

- [ ] introduce new symbol link source file(s) to be shared among infra code, web console frontend, and web console backend

2023-11-18 10:48 UTC, chenhaiyun commented on frontend/src/pages/pipelines/create/steps/buffer/BufferMSK.tsx
> +                            {!update ? (
This is a history bug?

2023-11-18 10:48 UTC, chenhaiyun commented on frontend/src/pages/analytics/comps/ExploreEmbedFrame.tsx
> +    <div id={'EmbedId'} className="iframe-explore">
id = 'EmbedId', no need {}

2023-11-18 10:48 UTC, chenhaiyun commented on frontend/src/pages/analytics/comps/ExploreEmbedFrame.tsx
> +import { t } from 'i18next';
```
import { useTranslation } from 'react-i18next';
const { t, i18n } = useTranslation();
```

2023-11-18 13:27 UTC, tyyzqmf commented on frontend/src/pages/pipelines/create/steps/buffer/BufferMSK.tsx
> +                            {!update ? (
yes

2023-11-18 15:16 UTC, chenhaiyun approved these changes

2023-11-18 15:18 UTC, zxkane requested changes

2023-11-18 15:18 UTC, zxkane commented on src/control-plane/backend/lambda/api/service/reporting.ts
> +        console.log(result);
use logger

2023-11-18 15:18 UTC, zxkane commented on src/control-plane/backend/lambda/api/model/stacks.ts
> +      throw new ClickStreamBadRequestError('ServerMax must greater than 1.');
-> must be greater

2023-11-19 13:41 UTC, zxkane approved these changes

2023-11-19 13:41 UTC, merged