fix: return pipeline details when execution no found
awslabs/clickstream-analytics-on-aws pull request #699
Opened 2023-12-14 07:50 UTC by tyyzqmf

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

## Summary

(describe what this merge request does)

## Implementation highlights

(describe how the merge request does for feature changes, share the RFC link if it has)

## Test checklist

- [ ] add new test cases
- [ ] all code changes are covered by unit tests
- [ ] end-to-end tests
  - [ ] deploy web console with CloudFront + S3 + API gateway
  - [ ] deploy web console within VPC
  - [ ] deploy ingestion server
    - [ ] with MSK sink
    - [ ] with KDS sink
    - [ ] with S3 sink
  - [ ] deploy data processing
  - [ ] deploy data modeling
    - [ ] new Redshift Serverless
    - [ ] provisioned Redshift
    - [ ] Athena
  - [ ] deploy with reporting

## Is it a breaking change

- [ ] add parameters without default value in stack
- [ ] introduce new service permission in stack
- [ ] introduce new top level stack module

## Miscellaneous

- [ ] introduce new symbol link source file(s) to be shared among infra code, web console frontend, and web console backend

2023-12-14 08:00 UTC, zxkane requested changes

2023-12-14 08:00 UTC, zxkane commented on src/control-plane/backend/lambda/api/service/stack.ts
> +      logger.error('get execution detail error ', { error });
Let's handle the known case of execution that does not exist.

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/sfn/command/DescribeExecutionCommand/

Also, I prefer to using `info` for known case and `warn` for logging other cases.

2023-12-15 06:31 UTC, zxkane approved these changes

2023-12-15 06:37 UTC, amliuyong approved these changes

2023-12-15 06:52 UTC, merged