chore: event trigger stack and state status change
awslabs/clickstream-analytics-on-aws pull request #735
Opened 2023-12-22 10:39 UTC by tyyzqmf

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

## Summary

(describe what this merge request does)

## Implementation highlights

(describe how the merge request does for feature changes, share the RFC link if it has)

## Test checklist

- [ ] add new test cases
- [ ] all code changes are covered by unit tests
- [ ] end-to-end tests
  - [ ] deploy web console with CloudFront + S3 + API gateway
  - [ ] deploy web console within VPC
  - [ ] deploy ingestion server
    - [ ] with MSK sink
    - [ ] with KDS sink
    - [ ] with S3 sink
  - [ ] deploy data processing
  - [ ] deploy data modeling
    - [ ] new Redshift Serverless
    - [ ] provisioned Redshift
    - [ ] Athena
  - [ ] deploy with reporting

## Is it a breaking change

- [ ] add parameters without default value in stack
- [ ] introduce new service permission in stack
- [ ] introduce new top level stack module

## Miscellaneous

- [ ] introduce new symbol link source file(s) to be shared among infra code, web console frontend, and web console backend

2023-12-25 05:13 UTC, zxkane requested changes
- Add test cases for new listenStackStatus and listenStateStatus functions
- Could it recover from below use cases? If so, add test cases for them.

1. manually recover from UPDATE_FAILED,
2. manually updating the VERSION tag of stack to make consistent to the one in DDB

2023-12-26 04:22 UTC, tyyzqmf commented on src/control-plane/backend/event-bus-construct.ts
> +        // resources: [`{ "wildcard": "arn:${Aws.PARTITION}:states:${Aws.REGION}:${Aws.ACCOUNT_ID}:execution:${props.listenStateMachine.stateMachineName}:main*" }`],
Yes, target lambda will filter execution use prefix `main` .

2023-12-26 04:30 UTC, tyyzqmf commented on src/control-plane/backend/lambda/api/model/pipeline.ts
> +    await createRuleAndAddTargets(
We will delete this rule when pipeline status change to DELETED in rule's target lambda.

2023-12-26 05:37 UTC, zxkane commented on src/control-plane/backend/event-bus-construct.ts
> +        // resources: [`{ "wildcard": "arn:${Aws.PARTITION}:states:${Aws.REGION}:${Aws.ACCOUNT_ID}:execution:${props.listenStateMachine.stateMachineName}:main*" }`],
Why not excluding other events via the rule? Any technical limitation.

2023-12-26 06:05 UTC, tyyzqmf commented on src/control-plane/backend/event-bus-construct.ts
> +        // resources: [`{ "wildcard": "arn:${Aws.PARTITION}:states:${Aws.REGION}:${Aws.ACCOUNT_ID}:execution:${props.listenStateMachine.stateMachineName}:main*" }`],
CDK not support create rule with wildcard filter.

2023-12-26 06:38 UTC, zxkane commented on src/control-plane/backend/event-bus-construct.ts
> +        // resources: [`{ "wildcard": "arn:${Aws.PARTITION}:states:${Aws.REGION}:${Aws.ACCOUNT_ID}:execution:${props.listenStateMachine.stateMachineName}:main*" }`],
If it's supported by L1, how about using [escape hatches](https://docs.aws.amazon.com/cdk/v2/guide/cfn_layer.html)?

2023-12-27 03:04 UTC, tyyzqmf commented on src/control-plane/backend/lambda/api/common/utils.ts
> +  } else if (executionDetail?.status === ExecutionStatus.RUNNING) {
INGs status include: Creating, Updating, Deleting, so it depend on **lastAction** in Line 1005.

2023-12-27 06:47 UTC, tyyzqmf commented on src/control-plane/backend/event-bus-construct.ts
> +        // resources: [`{ "wildcard": "arn:${Aws.PARTITION}:states:${Aws.REGION}:${Aws.ACCOUNT_ID}:execution:${props.listenStateMachine.stateMachineName}:main*" }`],
Use CfnRule addOverride to create wildcard filter.

2024-01-01 09:33 UTC, zxkane requested changes

2024-01-01 09:33 UTC, zxkane commented on src/control-plane/backend/lambda/api/store/aws/events.ts
> +    const command = new PutRuleCommand({
Let's propogate the tags too.

2024-01-01 09:33 UTC, zxkane commented on src/control-plane/backend/lambda/api/store/aws/sns.ts
> +    const command = new CreateTopicCommand({
Let's propogate the tags too.

2024-01-01 09:33 UTC, zxkane commented on src/control-plane/backend/lambda/api/store/aws/sns.ts
> +        {
Is it required by this policy?

2024-01-01 09:33 UTC, zxkane commented on src/control-plane/backend/lambda/api/test/api/application.test.ts
> +                            TemplateURL: 'https://xxx.com',
Let's use `example.com`

2024-01-01 09:33 UTC, zxkane commented on src/control-plane/backend/lambda/listen-stack-status/index.ts
> +    return;
This swallows this event. I prefer to throw the exception to retry it later.

2024-01-01 09:33 UTC, zxkane commented on src/control-plane/backend/lambda/listen-stack-status/index.ts
> +    return;
This swallows this event. I prefer to throw the exception to retry it later.

2024-01-01 09:33 UTC, zxkane commented on src/control-plane/backend/lambda/listen-stack-status/index.ts
> +    return;
This swallows this event. I prefer to throw the exception to retry it later.

2024-01-01 09:33 UTC, zxkane commented on src/control-plane/backend/lambda/listen-stack-status/index.ts
> +    logger.error('Failed to update pipeline stack status: ', { projectId, pipelineId, err });
This swallows this event. I prefer to throw the exception to retry it later.

2024-01-01 09:33 UTC, zxkane commented on src/control-plane/backend/lambda/listen-state-status/index.ts
> +    return;
This swallows this event. I prefer to throw the exception to retry it later.

2024-01-01 09:33 UTC, zxkane commented on src/control-plane/backend/lambda/listen-state-status/index.ts
> +const getPipeline = async (pipelineId: string) => {
try to share those duplicated method in those Lambda functions

2024-01-01 09:33 UTC, zxkane commented on src/control-plane/backend/lambda/listen-state-status/index.ts
> +const updatePipelineStateStatus = async (
share it

2024-01-01 09:33 UTC, zxkane commented on src/control-plane/backend/lambda/listen-state-status/index.ts
> +    logger.error('Failed to update pipeline state status: ', { projectId, pipelineId, err });
This swallows this event. I prefer to throw the exception to retry it later.

2024-01-01 09:33 UTC, zxkane commented on src/control-plane/backend/lambda/listen-state-status/index.ts
> +    logger.error('Failed to delete project: ', { projectId, err });
This swallows this event. I prefer to throw the exception to retry it later.

2024-01-01 09:33 UTC, zxkane commented on test.template.json
> +{
Is it used?

2024-01-02 02:26 UTC, tyyzqmf commented on frontend/src/apis/pipeline.ts
> +    `/pipeline/${params.projectId}?pid=${params.projectId}&refresh=${refreshParam}`
I will fix it in #738

2024-01-02 02:40 UTC, tyyzqmf commented on test.template.json
> +{
deleted.

2024-01-02 04:56 UTC, tyyzqmf commented on src/control-plane/backend/lambda/api/store/aws/sns.ts
> +        {
deleted it

2024-01-02 15:37 UTC, zxkane requested changes

2024-01-02 15:37 UTC, zxkane commented on src/control-plane/backend/lambda/api/store/aws/sns.ts
> +    console.error('Error in subscribe topic', { error });
use logger instead of console

2024-01-03 03:32 UTC, zxkane approved these changes

2024-01-03 03:56 UTC, merged