fix: Able to choose or input s3 bucket in another region
awslabs/clickstream-analytics-on-aws pull request #741
Opened 2023-12-26 11:24 UTC by tyyzqmf

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

## Summary

1. fix bucket check in backend.
2. clear selected bucket when region changed.

## Implementation highlights

(describe how the merge request does for feature changes, share the RFC link if it has)

## Test checklist

- [ ] add new test cases
- [ ] all code changes are covered by unit tests
- [ ] end-to-end tests
  - [ ] deploy web console with CloudFront + S3 + API gateway
  - [ ] deploy web console within VPC
  - [ ] deploy ingestion server
    - [ ] with MSK sink
    - [ ] with KDS sink
    - [ ] with S3 sink
  - [ ] deploy data processing
  - [ ] deploy data modeling
    - [ ] new Redshift Serverless
    - [ ] provisioned Redshift
    - [ ] Athena
  - [ ] deploy with reporting

## Is it a breaking change

- [ ] add parameters without default value in stack
- [ ] introduce new service permission in stack
- [ ] introduce new top level stack module

## Miscellaneous

- [ ] introduce new symbol link source file(s) to be shared among infra code, web console frontend, and web console backend

2023-12-26 15:13 UTC, zxkane requested changes

2023-12-26 15:13 UTC, zxkane commented on frontend/src/pages/pipelines/create/CreatePipeline.tsx
> +      if (!update) {
Let's add a new test case for changing the region when creating the pipeline.

2024-01-04 01:44 UTC, zxkane commented on frontend/src/pages/pipelines/create/CreatePipeline.tsx
> +      if (!update) {
It depends on the refactoring mechanism of testing frontend. Let include this case in the future refactoring.

2024-01-04 01:45 UTC, zxkane approved these changes

2024-01-04 01:45 UTC, zxkane requested changes
Resolve conflicts

2024-01-05 05:03 UTC, chenhaiyun approved these changes

2024-01-05 05:08 UTC, zxkane approved these changes

2024-01-05 05:27 UTC, merged