chore: add base library
awslabs/clickstream-analytics-on-aws pull request #889
Opened 2024-02-20 08:36 UTC by chenhaiyun

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

## Summary

(describe what this merge request does)

## Implementation highlights

(describe how the merge request does for feature changes, share the RFC link if it has)

## Test checklist

- [ ] add new test cases
- [ ] all code changes are covered by unit tests
- [ ] end-to-end tests
  - [ ] deploy web console with CloudFront + S3 + API gateway
  - [ ] deploy web console within VPC
  - [ ] deploy ingestion server
    - [ ] with MSK sink
    - [ ] with KDS sink
    - [ ] with S3 sink
  - [ ] deploy data processing
  - [ ] deploy data modeling
    - [ ] new Redshift Serverless
    - [ ] provisioned Redshift
    - [ ] Athena
  - [ ] deploy with reporting

## Is it a breaking change

- [ ] add parameters without default value in stack
- [ ] introduce new service permission in stack
- [ ] introduce new top level stack module

## Miscellaneous

- [ ] introduce new symbol link source file(s) to be shared among infra code, web console frontend, and web console backend

2024-02-26 16:10 UTC, zxkane requested changes
- [x] rename api project to `@aws/clickstream-web-console-api`
- [x] update README for how install tool and dependencies
- [x] update scripts in `src/control-plane/local`

2024-02-26 16:10 UTC, zxkane commented on src/control-plane/frontend/Dockerfile
> +COPY . .
It's not a best practice in security; we should avoid it.

2024-02-27 18:27 UTC, chenhaiyun commented on .github/workflows/build.yml
> +        run: pnpm i --no-frozen-lockfile
It's command was auto generated by projen config.

2024-02-28 03:28 UTC, tyyzqmf approved these changes

2024-02-28 03:33 UTC, zxkane approved these changes

2024-02-28 04:03 UTC, merged