Draft: Ingestion v2
awslabs/clickstream-analytics-on-aws pull request #896
Opened 2024-02-26 02:55 UTC by dengmingtong

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

## Summary

(describe what this merge request does)

## Implementation highlights

(describe how the merge request does for feature changes, share the RFC link if it has)

## Test checklist

- [ ] add new test cases
- [ ] all code changes are covered by unit tests
- [ ] end-to-end tests
  - [ ] deploy web console with CloudFront + S3 + API gateway
  - [ ] deploy web console within VPC
  - [ ] deploy ingestion server
    - [ ] with MSK sink
    - [ ] with KDS sink
    - [ ] with S3 sink
  - [ ] deploy data processing
  - [ ] deploy data modeling
    - [ ] new Redshift Serverless
    - [ ] provisioned Redshift
    - [ ] Athena
  - [ ] deploy with reporting

## Is it a breaking change

- [ ] add parameters without default value in stack
- [ ] introduce new service permission in stack
- [ ] introduce new top level stack module

## Miscellaneous

- [ ] introduce new symbol link source file(s) to be shared among infra code, web console frontend, and web console backend

2024-03-03 15:13 UTC, zxkane requested changes

2024-03-03 15:13 UTC, zxkane commented on src/ingestion-server/custom-resource/update-alb-rules-v2/index.ts
> +/**
What's the difference compared to the original `update-alb-rules`?

2024-03-03 15:13 UTC, zxkane commented on src/ingestion-server/server-v2/condition-v2.ts
it's unnecessary to add `v2` in file name if it's already named `server-v2`

2024-03-03 15:13 UTC, zxkane commented on src/ingestion-server/server-v2/condition-v2.ts
> +  const ecsEC2Condition = new CfnCondition(scope, 'ecsEC2Condition', {
What's the primary difference between the IaC code for Ec2 and Fargate?

2024-03-03 15:13 UTC, zxkane commented on src/ingestion-server/server-v2/condition-v2.ts
> +export function createKinesisConditionsV2(
It's no difference whether KDS is provisioned or on demand.

2024-03-03 15:13 UTC, zxkane commented on src/ingestion-server/server-v2/private/alb-v2.ts
> +  // service: BaseService;
remove commeted code

2024-03-03 15:13 UTC, zxkane commented on src/ingestion-server/server-v2/private/ecs-ec2-cluster.ts
> +  const isArm = ecsAsgSetting.isArm;
use arch instead

2024-06-05 08:31 UTC, dengmingtong commented on src/ingestion-server-v2-stack.ts
> +  readonly logBucketName?: string;
Done

2024-06-16 15:46 UTC, zxkane commented
### SonarQube Quality Gate Result
- **Result**: :exclamation: Error
- Triggered by @dengmingtong on `pull_request`

| Metric | Status | Value | Error Threshold |
|:------:|:------:|:-----:|:---------------:|
|Reliability rating|:white_check_mark: OK|1|> 1|
|Security rating|:white_check_mark: OK|1|> 1|
|Sqale rating|:white_check_mark: OK|1|> 1|
|Coverage|:white_check_mark: OK|83.60|< 80|
|Duplicated lines density|:white_check_mark: OK|5.20|> 30|
|Blocker violations|:white_check_mark: OK|0|> 0|
|Bugs|:white_check_mark: OK|0|> 0|
|Code smells|:white_check_mark: OK|13|> 40|
|Critical violations|:white_check_mark: OK|0|> 0|
|Major violations|:exclamation: Error|4|> 0|
|Security hotspots reviewed|:exclamation: Error|0|< 100|
|Vulnerabilities|:white_check_mark: OK|0|> 0|

[View on SonarQube](http://sonarqube:9000/dashboard?id=pr-896)
###### _updated: 6/16/2024, 15:46:27 (UTC+0)_

2024-06-16 15:46 UTC, zxkane commented
# SonarQube Code Analytics
## Quality Gate failed

![failed](https://hsonar.s3.ap-southeast-1.amazonaws.com/images/failed.png)

## Additional information
*The following metrics might not affect the Quality Gate status but improving them will improve your project code quality.*

## Issues
![bug](https://hsonar.s3.ap-southeast-1.amazonaws.com/images/bug.png)   [0 Bugs](http://sonarqube:9000/project/issues?id=pr-896&resolved=false&sinceLeakPeriod=true&types=BUG)

![vulnerability](https://hsonar.s3.ap-southeast-1.amazonaws.com/images/vulnerability.png)   [0 Vulnerabilities](http://sonarqube:9000/project/issues?id=pr-896&resolved=false&sinceLeakPeriod=true&types=VULNERABILITY)

![code_smell](https://hsonar.s3.ap-southeast-1.amazonaws.com/images/code_smell.png)   [0 Code Smells](http://sonarqube:9000/project/issues?id=pr-896&resolved=false&sinceLeakPeriod=true&types=CODE_SMELL)

## Coverage and Duplications
*No data* **Coverage**

*No data* **Duplication**

2024-06-17 02:58 UTC, zxkane commented
### SonarQube Quality Gate Result
- **Result**: :exclamation: Error
- Triggered by @dengmingtong on `pull_request`

| Metric | Status | Value | Error Threshold |
|:------:|:------:|:-----:|:---------------:|
|Reliability rating|:white_check_mark: OK|1|> 1|
|Security rating|:white_check_mark: OK|1|> 1|
|Sqale rating|:white_check_mark: OK|1|> 1|
|Coverage|:white_check_mark: OK|83.70|< 80|
|Duplicated lines density|:white_check_mark: OK|5.20|> 30|
|Blocker violations|:white_check_mark: OK|0|> 0|
|Bugs|:white_check_mark: OK|0|> 0|
|Code smells|:white_check_mark: OK|13|> 40|
|Critical violations|:white_check_mark: OK|0|> 0|
|Major violations|:exclamation: Error|4|> 0|
|Security hotspots reviewed|:exclamation: Error|0|< 100|
|Vulnerabilities|:white_check_mark: OK|0|> 0|

[View on SonarQube](http://sonarqube:9000/dashboard?id=pr-896)
###### _updated: 6/17/2024, 02:58:39 (UTC+0)_

2024-06-17 03:28 UTC, zxkane commented
### SonarQube Quality Gate Result
- **Result**: :exclamation: Error
- Triggered by @zxkane on `pull_request`

| Metric | Status | Value | Error Threshold |
|:------:|:------:|:-----:|:---------------:|
|Reliability rating|:white_check_mark: OK|1|> 1|
|Security rating|:white_check_mark: OK|1|> 1|
|Sqale rating|:white_check_mark: OK|1|> 1|
|Coverage|:white_check_mark: OK|83.70|< 80|
|Duplicated lines density|:white_check_mark: OK|5.20|> 30|
|Blocker violations|:white_check_mark: OK|0|> 0|
|Bugs|:white_check_mark: OK|0|> 0|
|Code smells|:white_check_mark: OK|13|> 40|
|Critical violations|:white_check_mark: OK|0|> 0|
|Major violations|:exclamation: Error|4|> 0|
|Security hotspots reviewed|:exclamation: Error|0|< 100|
|Vulnerabilities|:white_check_mark: OK|0|> 0|

[View on SonarQube](http://sonarqube:9000/dashboard?id=pr-896)
###### _updated: 6/17/2024, 03:28:30 (UTC+0)_

2024-06-19 03:01 UTC, zxkane commented
### SonarQube Quality Gate Result
- **Result**: :exclamation: Error
- Triggered by @dengmingtong on `pull_request`

| Metric | Status | Value | Error Threshold |
|:------:|:------:|:-----:|:---------------:|
|Reliability rating|:white_check_mark: OK|1|> 1|
|Security rating|:white_check_mark: OK|1|> 1|
|Sqale rating|:white_check_mark: OK|1|> 1|
|Coverage|:white_check_mark: OK|83.80|< 80|
|Duplicated lines density|:white_check_mark: OK|5.20|> 30|
|Blocker violations|:white_check_mark: OK|0|> 0|
|Bugs|:white_check_mark: OK|0|> 0|
|Code smells|:white_check_mark: OK|14|> 40|
|Critical violations|:white_check_mark: OK|0|> 0|
|Major violations|:exclamation: Error|5|> 0|
|Security hotspots reviewed|:exclamation: Error|0|< 100|
|Vulnerabilities|:white_check_mark: OK|0|> 0|

[View on SonarQube](http://sonarqube:9000/dashboard?id=pr-896)
###### _updated: 6/19/2024, 03:01:28 (UTC+0)_

2024-06-19 03:34 UTC, zxkane commented
### SonarQube Quality Gate Result
- **Result**: :exclamation: Error
- Triggered by @dengmingtong on `pull_request`

| Metric | Status | Value | Error Threshold |
|:------:|:------:|:-----:|:---------------:|
|Reliability rating|:white_check_mark: OK|1|> 1|
|Security rating|:white_check_mark: OK|1|> 1|
|Sqale rating|:white_check_mark: OK|1|> 1|
|Coverage|:white_check_mark: OK|83.80|< 80|
|Duplicated lines density|:white_check_mark: OK|5.30|> 30|
|Blocker violations|:white_check_mark: OK|0|> 0|
|Bugs|:white_check_mark: OK|0|> 0|
|Code smells|:white_check_mark: OK|10|> 40|
|Critical violations|:white_check_mark: OK|0|> 0|
|Major violations|:exclamation: Error|1|> 0|
|Security hotspots reviewed|:exclamation: Error|0|< 100|
|Vulnerabilities|:white_check_mark: OK|0|> 0|

[View on SonarQube](http://sonarqube:9000/dashboard?id=pr-896)
###### _updated: 6/19/2024, 03:34:44 (UTC+0)_

2024-06-19 06:31 UTC, zxkane requested changes

2024-06-19 06:31 UTC, zxkane commented on src/ingestion-server/custom-resource/update-alb-rules/index.ts
> +  readonly enableAuthentication: string;
we might refactor it as 

```ts
interface Input {
readonly arn: string;
readonly new: PropType;
readonly old: PropType;
}
```

2024-06-19 06:31 UTC, zxkane commented on src/ingestion-server/custom-resource/update-alb-rules/index.ts
> +  if (enableAuthentication === 'Yes') {
As in the previous comment, create an enum type for the value Yes and No.

2024-06-19 06:31 UTC, zxkane commented on src/ingestion-server/custom-resource/update-alb-rules/index.ts
> +    await sleep(20000);
Why are we using a fixed value here?

2024-06-19 06:31 UTC, zxkane commented on src/ingestion-server/server-v2/ingestion-server-v2.ts
>  function deleteECSCluster(scope: Construct, ecsClusterArn: string, ecsClusterName: string, ecsServiceName: string) {
change to `createDeleteECSClusterHook` is better

2024-06-19 06:31 UTC, zxkane commented on src/ingestion-server/server-v2/private/ecs-ec2-service.ts
> +export interface Ec2ServiceProps extends ECSClusterProps {
Should we have shared an abstract class for sharing the common configuration?

2024-06-19 06:31 UTC, zxkane commented on src/ingestion-server/server/parameter.ts
> +  const notificationsTopicArnParam = new CfnParameter(
I think it's useless. Could we remove it?

2024-06-19 12:16 UTC, amliuyong commented
<img width="859" alt="image" src="https://github.com/awslabs/clickstream-analytics-on-aws/assets/23469402/ef001ec6-e44b-4438-b068-958443ff8489">

2024-06-21 03:41 UTC, zxkane commented
### SonarQube Quality Gate Result
- **Result**: :exclamation: Error
- Triggered by @dengmingtong on `pull_request`

| Metric | Status | Value | Error Threshold |
|:------:|:------:|:-----:|:---------------:|
|Reliability rating|:white_check_mark: OK|1|> 1|
|Security rating|:white_check_mark: OK|1|> 1|
|Sqale rating|:white_check_mark: OK|1|> 1|
|Coverage|:white_check_mark: OK|83.80|< 80|
|Duplicated lines density|:white_check_mark: OK|5.10|> 30|
|Blocker violations|:white_check_mark: OK|0|> 0|
|Bugs|:white_check_mark: OK|0|> 0|
|Code smells|:white_check_mark: OK|11|> 40|
|Critical violations|:white_check_mark: OK|0|> 0|
|Major violations|:exclamation: Error|2|> 0|
|Security hotspots reviewed|:exclamation: Error|0|< 100|
|Vulnerabilities|:white_check_mark: OK|0|> 0|

[View on SonarQube](http://sonarqube:9000/dashboard?id=pr-896)
###### _updated: 6/21/2024, 03:41:28 (UTC+0)_

2024-06-21 04:12 UTC, zxkane commented
### SonarQube Quality Gate Result
- **Result**: :exclamation: Error
- Triggered by @zxkane on `pull_request`

| Metric | Status | Value | Error Threshold |
|:------:|:------:|:-----:|:---------------:|
|Reliability rating|:white_check_mark: OK|1|> 1|
|Security rating|:white_check_mark: OK|1|> 1|
|Sqale rating|:white_check_mark: OK|1|> 1|
|Coverage|:white_check_mark: OK|83.80|< 80|
|Duplicated lines density|:white_check_mark: OK|5.10|> 30|
|Blocker violations|:white_check_mark: OK|0|> 0|
|Bugs|:white_check_mark: OK|0|> 0|
|Code smells|:white_check_mark: OK|11|> 40|
|Critical violations|:white_check_mark: OK|0|> 0|
|Major violations|:exclamation: Error|2|> 0|
|Security hotspots reviewed|:exclamation: Error|0|< 100|
|Vulnerabilities|:white_check_mark: OK|0|> 0|

[View on SonarQube](http://sonarqube:9000/dashboard?id=pr-896)
###### _updated: 6/21/2024, 04:12:53 (UTC+0)_

2024-06-21 05:09 UTC, zxkane commented
### SonarQube Quality Gate Result
- **Result**: :exclamation: Error
- Triggered by @dengmingtong on `pull_request`

| Metric | Status | Value | Error Threshold |
|:------:|:------:|:-----:|:---------------:|
|Reliability rating|:white_check_mark: OK|1|> 1|
|Security rating|:white_check_mark: OK|1|> 1|
|Sqale rating|:white_check_mark: OK|1|> 1|
|Coverage|:white_check_mark: OK|83.80|< 80|
|Duplicated lines density|:white_check_mark: OK|5.10|> 30|
|Blocker violations|:white_check_mark: OK|0|> 0|
|Bugs|:white_check_mark: OK|0|> 0|
|Code smells|:white_check_mark: OK|10|> 40|
|Critical violations|:white_check_mark: OK|0|> 0|
|Major violations|:exclamation: Error|1|> 0|
|Security hotspots reviewed|:exclamation: Error|0|< 100|
|Vulnerabilities|:white_check_mark: OK|0|> 0|

[View on SonarQube](http://sonarqube:9000/dashboard?id=pr-896)
###### _updated: 6/21/2024, 05:09:52 (UTC+0)_

2024-06-21 05:39 UTC, zxkane commented
### SonarQube Quality Gate Result
- **Result**: :exclamation: Error
- Triggered by @zxkane on `pull_request`

| Metric | Status | Value | Error Threshold |
|:------:|:------:|:-----:|:---------------:|
|Reliability rating|:white_check_mark: OK|1|> 1|
|Security rating|:white_check_mark: OK|1|> 1|
|Sqale rating|:white_check_mark: OK|1|> 1|
|Coverage|:white_check_mark: OK|83.80|< 80|
|Duplicated lines density|:white_check_mark: OK|5.10|> 30|
|Blocker violations|:white_check_mark: OK|0|> 0|
|Bugs|:white_check_mark: OK|0|> 0|
|Code smells|:white_check_mark: OK|10|> 40|
|Critical violations|:white_check_mark: OK|0|> 0|
|Major violations|:exclamation: Error|1|> 0|
|Security hotspots reviewed|:exclamation: Error|0|< 100|
|Vulnerabilities|:white_check_mark: OK|0|> 0|

[View on SonarQube](http://sonarqube:9000/dashboard?id=pr-896)
###### _updated: 6/21/2024, 05:39:28 (UTC+0)_

2024-06-21 07:36 UTC, zxkane commented
### SonarQube Quality Gate Result
- **Result**: :exclamation: Error
- Triggered by @dengmingtong on `pull_request`

| Metric | Status | Value | Error Threshold |
|:------:|:------:|:-----:|:---------------:|
|Reliability rating|:white_check_mark: OK|1|> 1|
|Security rating|:white_check_mark: OK|1|> 1|
|Sqale rating|:white_check_mark: OK|1|> 1|
|Coverage|:white_check_mark: OK|83.80|< 80|
|Duplicated lines density|:white_check_mark: OK|5.10|> 30|
|Blocker violations|:white_check_mark: OK|0|> 0|
|Bugs|:white_check_mark: OK|0|> 0|
|Code smells|:white_check_mark: OK|9|> 40|
|Critical violations|:white_check_mark: OK|0|> 0|
|Major violations|:white_check_mark: OK|0|> 0|
|Security hotspots reviewed|:exclamation: Error|0|< 100|
|Vulnerabilities|:white_check_mark: OK|0|> 0|

[View on SonarQube](http://sonarqube:9000/dashboard?id=pr-896)
###### _updated: 6/21/2024, 07:36:55 (UTC+0)_

2024-06-21 08:05 UTC, zxkane commented
### SonarQube Quality Gate Result
- **Result**: :exclamation: Error
- Triggered by @zxkane on `pull_request`

| Metric | Status | Value | Error Threshold |
|:------:|:------:|:-----:|:---------------:|
|Reliability rating|:white_check_mark: OK|1|> 1|
|Security rating|:white_check_mark: OK|1|> 1|
|Sqale rating|:white_check_mark: OK|1|> 1|
|Coverage|:white_check_mark: OK|83.80|< 80|
|Duplicated lines density|:white_check_mark: OK|5.10|> 30|
|Blocker violations|:white_check_mark: OK|0|> 0|
|Bugs|:white_check_mark: OK|0|> 0|
|Code smells|:white_check_mark: OK|9|> 40|
|Critical violations|:white_check_mark: OK|0|> 0|
|Major violations|:white_check_mark: OK|0|> 0|
|Security hotspots reviewed|:exclamation: Error|0|< 100|
|Vulnerabilities|:white_check_mark: OK|0|> 0|

[View on SonarQube](http://sonarqube:9000/dashboard?id=pr-896)
###### _updated: 6/21/2024, 08:05:17 (UTC+0)_

2024-06-21 10:24 UTC, amliuyong commented
![image](https://github.com/awslabs/clickstream-analytics-on-aws/assets/23469402/3947b269-8ed9-4675-8eb0-451c4008bf3e)

2024-06-21 11:09 UTC, zxkane commented
### SonarQube Quality Gate Result
- **Result**: :exclamation: Error
- Triggered by @zxkane on `pull_request`

| Metric | Status | Value | Error Threshold |
|:------:|:------:|:-----:|:---------------:|
|Reliability rating|:white_check_mark: OK|1|> 1|
|Security rating|:white_check_mark: OK|1|> 1|
|Sqale rating|:white_check_mark: OK|1|> 1|
|Coverage|:white_check_mark: OK|83.80|< 80|
|Duplicated lines density|:white_check_mark: OK|5.10|> 30|
|Blocker violations|:white_check_mark: OK|0|> 0|
|Bugs|:white_check_mark: OK|0|> 0|
|Code smells|:white_check_mark: OK|9|> 40|
|Critical violations|:white_check_mark: OK|0|> 0|
|Major violations|:white_check_mark: OK|0|> 0|
|Security hotspots reviewed|:exclamation: Error|0|< 100|
|Vulnerabilities|:white_check_mark: OK|0|> 0|

[View on SonarQube](http://sonarqube:9000/dashboard?id=pr-896)
###### _updated: 6/21/2024, 11:09:04 (UTC+0)_

2024-06-21 13:19 UTC, zxkane commented
### SonarQube Quality Gate Result
- **Result**: :white_check_mark: OK
- Triggered by @dengmingtong on `pull_request`

| Metric | Status | Value | Error Threshold |
|:------:|:------:|:-----:|:---------------:|
|Reliability rating|:white_check_mark: OK|1|> 1|
|Security rating|:white_check_mark: OK|1|> 1|
|Sqale rating|:white_check_mark: OK|1|> 1|
|Coverage|:white_check_mark: OK|83.80|< 80|
|Duplicated lines density|:white_check_mark: OK|5.10|> 30|
|Blocker violations|:white_check_mark: OK|0|> 0|
|Bugs|:white_check_mark: OK|0|> 0|
|Code smells|:white_check_mark: OK|9|> 40|
|Critical violations|:white_check_mark: OK|0|> 0|
|Major violations|:white_check_mark: OK|0|> 0|
|Vulnerabilities|:white_check_mark: OK|0|> 0|

[View on SonarQube](http://sonarqube:9000/dashboard?id=pr-896)
###### _updated: 6/21/2024, 13:19:07 (UTC+0)_

2024-06-23 08:29 UTC, zxkane requested changes

2024-06-23 08:29 UTC, zxkane commented on src/ingestion-server/custom-resource/update-alb-rules.ts
> +  enableAuthentication: string;
use `FeatureFlag`

2024-06-24 02:27 UTC, zxkane approved these changes

2024-06-24 02:57 UTC, merged