QuickSight Supporting in CN regions
awslabs/clickstream-analytics-on-aws pull request #898
Opened 2024-02-26 14:07 UTC by tyyzqmf

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

## Summary

1. If it is the third step of creating pipelines in China regions, a user must be selected to create preset QuickSight resources. And global region unchanged.
2. 

## Implementation highlights

(describe how the merge request does for feature changes, share the RFC link if it has)

## Test checklist

- [ ] add new test cases
- [ ] all code changes are covered by unit tests
- [ ] end-to-end tests
  - [ ] deploy web console with CloudFront + S3 + API gateway
  - [ ] deploy web console within VPC
  - [ ] deploy ingestion server
    - [ ] with MSK sink
    - [ ] with KDS sink
    - [ ] with S3 sink
  - [ ] deploy data processing
  - [ ] deploy data modeling
    - [ ] new Redshift Serverless
    - [ ] provisioned Redshift
    - [ ] Athena
  - [ ] deploy with reporting

## Is it a breaking change

- [ ] add parameters without default value in stack
- [ ] introduce new service permission in stack
- [ ] introduce new top level stack module

## Miscellaneous

- [ ] introduce new symbol link source file(s) to be shared among infra code, web console frontend, and web console backend

2024-02-27 15:15 UTC, zxkane requested changes
update docs as well

2024-02-28 01:58 UTC, chenhaiyun commented on frontend/public/locales/en-US/pipeline.json
> +    "quickSightUser": "QuickSight user",
No zh-CN translation file?

2024-02-28 02:47 UTC, tyyzqmf commented on frontend/public/locales/en-US/pipeline.json
> +    "quickSightUser": "QuickSight user",
added

2024-02-28 06:10 UTC, zxkane commented on src/control-plane/backend/lambda/api/model/pipeline.ts
> +            publishUserName: this.pipeline.reporting.quickSight?.user?.split('/').pop() ?? '',
Let's do it in a separate PR.

2024-02-28 09:08 UTC, zxkane approved these changes

2024-02-28 14:57 UTC, merged