Explorative schema v2
awslabs/clickstream-analytics-on-aws pull request #953
Opened 2024-03-07 06:33 UTC by llmin

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

## Summary

(describe what this merge request does)

## Implementation highlights

(describe how the merge request does for feature changes, share the RFC link if it has)

## Test checklist

- [ ] add new test cases
- [ ] all code changes are covered by unit tests
- [ ] end-to-end tests
  - [ ] deploy web console with CloudFront + S3 + API gateway
  - [ ] deploy web console within VPC
  - [ ] deploy ingestion server
    - [ ] with MSK sink
    - [ ] with KDS sink
    - [ ] with S3 sink
  - [ ] deploy data processing
  - [ ] deploy data modeling
    - [ ] new Redshift Serverless
    - [ ] provisioned Redshift
    - [ ] Athena
  - [ ] deploy with reporting
  - [ ] streaming ingestion
    - [ ] with Redshift Serverless
    - [ ] with provisioned Redshift

## Is it a breaking change

- [ ] add parameters without default value in stack
- [ ] introduce new service permission in stack
- [ ] introduce new top level stack module

## Miscellaneous

- [ ] introduce new symbol link source file(s) to be shared among infra code, web console frontend, and web console backend

2024-03-09 10:30 UTC, zxkane requested changes

2024-03-09 10:30 UTC, zxkane commented on src/control-plane/backend/lambda/api/common/explore-types.ts
> +  PAGE_TITLE = 'page_title',
I see the duplicated `ExplorePathNodeType` in `frontend/src/ts/explore-types.ts`.

We need extract them to base lib.

2024-04-01 02:59 UTC, tyyzqmf approved these changes

2024-04-01 03:26 UTC, dengmingtong approved these changes

2024-04-01 08:03 UTC, zxkane commented on src/control-plane/backend/lambda/api/test/api/metadata.test.ts
> -      category: ConditionCategory.APP_INFO,
Why not use the constant?

2024-04-01 08:03 UTC, zxkane commented on src/control-plane/backend/lambda/api/test/api/metadata.test.ts
> +      .get(`/api/metadata/event_parameter?projectId=${MOCK_PROJECT_ID}&appId=${MOCK_APP_ID}&name=${MOCK_EVENT_PARAMETER_NAME}&category=app_info&type=${MetadataValueType.STRING}`);
Why not use the constant?

2024-04-01 13:20 UTC, llmin commented on src/control-plane/backend/lambda/api/test/api/metadata.test.ts
> -      category: ConditionCategory.APP_INFO,
fixed

2024-04-01 13:20 UTC, llmin commented on src/control-plane/backend/lambda/api/service/quicksight/sql-builder.ts
> +//todo event_date
remove

2024-04-01 14:35 UTC, zxkane approved these changes

2024-04-01 14:57 UTC, merged