chore: Handling special characters when saving dashboard
awslabs/clickstream-analytics-on-aws pull request #955
Opened 2024-03-08 03:55 UTC by tyyzqmf

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

## Summary

(describe what this merge request does)

## Implementation highlights

(describe how the merge request does for feature changes, share the RFC link if it has)

## Test checklist

- [ ] add new test cases
- [ ] all code changes are covered by unit tests
- [ ] end-to-end tests
  - [ ] deploy web console with CloudFront + S3 + API gateway
  - [ ] deploy web console within VPC
  - [ ] deploy ingestion server
    - [ ] with MSK sink
    - [ ] with KDS sink
    - [ ] with S3 sink
  - [ ] deploy data processing
  - [ ] deploy data modeling
    - [ ] new Redshift Serverless
    - [ ] provisioned Redshift
    - [ ] Athena
  - [ ] deploy with reporting
  - [ ] streaming ingestion
    - [ ] with Redshift Serverless
    - [ ] with provisioned Redshift

## Is it a breaking change

- [ ] add parameters without default value in stack
- [ ] introduce new service permission in stack
- [ ] introduce new top level stack module

## Miscellaneous

- [ ] introduce new symbol link source file(s) to be shared among infra code, web console frontend, and web console backend

2024-03-08 06:11 UTC, zxkane reviewed
@luorobin-a2z Should we silently remove the illegal characters in dashboard title? or just refuse the saving if the title contains illegal characters?

2024-03-11 13:08 UTC, tyyzqmf commented
> > @luorobin-a2z Should we silently remove the illegal characters in dashboard title? or just refuse the saving if the title contains illegal characters?
> 
> I suggest we reject saving and display warning message to ask user to reword the title.

Web console will show warning message when illegal characters in  dashboard title and subtitle

2024-03-12 02:30 UTC, zxkane requested changes

2024-03-12 02:30 UTC, zxkane commented on src/control-plane/backend/lambda/api/service/quicksight/reporting-check.ts
> +      this.params.chartTitle = replaceSpecialCharacters(this.params.chartTitle);
Let's keep the behavior the same as the frontend. Return a bad request if the input contains illegal characters.

2024-03-12 11:31 UTC, zxkane approved these changes

2024-03-12 11:55 UTC, merged