chore: Use decorator to mark the version range of stack parameters
awslabs/clickstream-analytics-on-aws pull request #987
Opened 2024-03-20 13:33 UTC by tyyzqmf

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

## Summary

1. Use decorator to mark the version range of stack parameters: `[*, v1.1.0]`, `[v1.1.0, v1.1.5]`, `[v1.1.0, *]`
2. Generate parameters based on the version of the pipeline, Instead of the current control plane version

## Implementation highlights

(describe how the merge request does for feature changes, share the RFC link if it has)

## Test checklist

- [ ] add new test cases
- [ ] all code changes are covered by unit tests
- [ ] end-to-end tests
  - [ ] deploy web console with CloudFront + S3 + API gateway
  - [ ] deploy web console within VPC
  - [ ] deploy ingestion server
    - [ ] with MSK sink
    - [ ] with KDS sink
    - [ ] with S3 sink
  - [ ] deploy data processing
  - [ ] deploy data modeling
    - [ ] new Redshift Serverless
    - [ ] provisioned Redshift
    - [ ] Athena
  - [ ] deploy with reporting
  - [ ] streaming ingestion
    - [ ] with Redshift Serverless
    - [ ] with provisioned Redshift

## Is it a breaking change

- [ ] add parameters without default value in stack
- [ ] introduce new service permission in stack
- [ ] introduce new top level stack module

## Miscellaneous

- [ ] introduce new symbol link source file(s) to be shared among infra code, web console frontend, and web console backend

2024-03-21 07:27 UTC, zxkane requested changes

2024-03-21 07:27 UTC, zxkane commented on src/control-plane/backend/lambda/api/test/api/workflow-version.test.ts
> +// const DataProcessingStackV1 = {
remove it

2024-03-21 07:51 UTC, tyyzqmf commented on src/control-plane/backend/lambda/api/model/stacks.ts
> +  @JSONObject.optional('')
This annotation cannot be deleted, and `@JSONObject.custom` will not executed after delete that.

2024-03-24 07:48 UTC, zxkane requested changes

2024-03-24 07:48 UTC, zxkane commented on src/common/solution-info.ts
> +  static V1_0_0 = 'v1.0.0';
manage versions like this,

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_rds.PostgresEngineVersion.html

2024-03-25 04:26 UTC, zxkane commented on src/control-plane/backend/lambda/api/model/stacks.ts
> +export function getStackParameters(stack: JSONObject, version: string): Parameter[] {
Should we update to `SolutionVersion` instead of `string`?

2024-03-25 04:26 UTC, zxkane commented on src/control-plane/backend/lambda/api/common/parameter-reflect.ts
> +export function isSupportVersion(stack: JSONObject, key: string, version: string) : boolean {
Should we update to `SolutionVersion` instead of `string`?

2024-03-25 04:26 UTC, zxkane commented on src/control-plane/backend/lambda/api/store/aws/quicksight.ts
> +export const getClickstreamUserArn = async (templateVersion: string, userArn: string): Promise<QuickSightUserArns> => {
Should we update to `SolutionVersion` instead of `string`?

2024-03-25 06:21 UTC, zxkane approved these changes

2024-03-25 06:43 UTC, merged